language: go
sudo: required

services:
  - docker

go:
  - 1.9

before_install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -u github.com/kardianos/govendor

script:
  - make --output-sync -j builder all
