comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

ignore:
  - '*.pb.go'
  - 'bindata.go'
  - 'aws/**'
  - 'vendor/**'

coverage:
  precision: 2
  round: up

github_checks:
    annotations: false
