START TRANSACTION;
LOCK TABLE htb_classid IN ACCESS EXCLUSIVE MODE;
LOCK TABLE trunk_enis IN ACCESS EXCLUSIVE MODE;
ALTER TABLE trunk_enis ALTER COLUMN id TYPE BIGINT;
ALTER TABLE htb_classid ALTER COLUMN trunk_eni TYPE BIGINT;
ALTER SEQUENCE trunk_enis_id_seq AS BIGINT NO CYCLE;
COMMIT;