START TRANSACTION;
LOCK TABLE htb_classid ACCESS EXCLUSIVE
LOCK TABLE trunk_enis ACCESS EXCLUSIVE
ALTER SEQUENCE trunk_enis_id_seq AS INTEGER NO CYCLE;
ALTER TABLE trunk_enis ALTER COLUMN id TYPE INTEGER;
ALTER TABLE htb_classid ALTER COLUMN trunk_eni TYPE INTEGER;
COMMIT;