START TRANSACTION;
LOCK TABLE htb_classid ACCESS EXCLUSIVE
LOCK TABLE trunk_enis ACCESS EXCLUSIVE
ALTER TABLE trunk_enis ALTER COLUMN id TYPE BIGINT;
ALTER TABLE htb_classid ALTER COLUMN trunk_eni TYPE BIGINT;
ALTER SEQUENCE trunk_enis_id_seq AS BIGINT NO CYCLE;
COMMIT;
VACUUM FULL htb_classid;
VACUUM FULL trunk_enis;