// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netflix/titus/titus_base.proto

package titus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Titus scheduler tier (see Titus scheduler documentation for more information).
type Tier int32

const (
	// / Tier for running latency insensitive batch workloads.
	Tier_Flex Tier = 0
	// / Tier for running latency sensitive workloads.
	Tier_Critical Tier = 1
)

var Tier_name = map[int32]string{
	0: "Flex",
	1: "Critical",
}
var Tier_value = map[string]int32{
	"Flex":     0,
	"Critical": 1,
}

func (x Tier) String() string {
	return proto.EnumName(Tier_name, int32(x))
}
func (Tier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{0}
}

// / Titus hierarchy level.
type Level int32

const (
	Level_SystemLevel        Level = 0
	Level_TierLevel          Level = 1
	Level_CapacityGroupLevel Level = 2
	Level_JobLevel           Level = 3
	Level_TaskLevel          Level = 4
)

var Level_name = map[int32]string{
	0: "SystemLevel",
	1: "TierLevel",
	2: "CapacityGroupLevel",
	3: "JobLevel",
	4: "TaskLevel",
}
var Level_value = map[string]int32{
	"SystemLevel":        0,
	"TierLevel":          1,
	"CapacityGroupLevel": 2,
	"JobLevel":           3,
	"TaskLevel":          4,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}
func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{1}
}

// / Disk mount permission mask
type MountPerm int32

const (
	// / Read only
	MountPerm_RO MountPerm = 0
	// Write only
	MountPerm_WO MountPerm = 1
	// Read/write
	MountPerm_RW MountPerm = 2
)

var MountPerm_name = map[int32]string{
	0: "RO",
	1: "WO",
	2: "RW",
}
var MountPerm_value = map[string]int32{
	"RO": 0,
	"WO": 1,
	"RW": 2,
}

func (x MountPerm) String() string {
	return proto.EnumName(MountPerm_name, int32(x))
}
func (MountPerm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{2}
}

type Day int32

const (
	Day_Monday    Day = 0
	Day_Tuesday   Day = 1
	Day_Wednesday Day = 2
	Day_Thursday  Day = 3
	Day_Friday    Day = 4
	Day_Saturday  Day = 5
	Day_Sunday    Day = 6
)

var Day_name = map[int32]string{
	0: "Monday",
	1: "Tuesday",
	2: "Wednesday",
	3: "Thursday",
	4: "Friday",
	5: "Saturday",
	6: "Sunday",
}
var Day_value = map[string]int32{
	"Monday":    0,
	"Tuesday":   1,
	"Wednesday": 2,
	"Thursday":  3,
	"Friday":    4,
	"Saturday":  5,
	"Sunday":    6,
}

func (x Day) String() string {
	return proto.EnumName(Day_name, int32(x))
}
func (Day) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{3}
}

// / Call metadata (caller's identity, call path).
type CallMetadata struct {
	// / (Required) The original caller identifier. Depending on the user identity (a user or an application), the format
	// of the id may be different. For example a user's id could be encoded as 'user:<email-address>', and
	// application id as 'app:<aws-account-id>:<app-name>:<app-stack>'.
	CallerId string `protobuf:"bytes,1,opt,name=callerId,proto3" json:"callerId,omitempty"`
	// / (Optional) The reason why a call was made.
	CallReason string `protobuf:"bytes,2,opt,name=callReason,proto3" json:"callReason,omitempty"`
	// / (Optional) The list of intermediaries via which a call was relayed.
	CallPath []string `protobuf:"bytes,3,rep,name=callPath,proto3" json:"callPath,omitempty"`
	// / (Optional) If set to true, a diagnostic information is provided if a request fails.
	Debug                bool     `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallMetadata) Reset()         { *m = CallMetadata{} }
func (m *CallMetadata) String() string { return proto.CompactTextString(m) }
func (*CallMetadata) ProtoMessage()    {}
func (*CallMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{0}
}
func (m *CallMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallMetadata.Unmarshal(m, b)
}
func (m *CallMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallMetadata.Marshal(b, m, deterministic)
}
func (dst *CallMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallMetadata.Merge(dst, src)
}
func (m *CallMetadata) XXX_Size() int {
	return xxx_messageInfo_CallMetadata.Size(m)
}
func (m *CallMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CallMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CallMetadata proto.InternalMessageInfo

func (m *CallMetadata) GetCallerId() string {
	if m != nil {
		return m.CallerId
	}
	return ""
}

func (m *CallMetadata) GetCallReason() string {
	if m != nil {
		return m.CallReason
	}
	return ""
}

func (m *CallMetadata) GetCallPath() []string {
	if m != nil {
		return m.CallPath
	}
	return nil
}

func (m *CallMetadata) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

// / An entity representing single page of a collection. Prefer using cursor-based pagination, pageNumber is being retired.
//  For the first page, leave both pageNumber and cursor empty.
type Page struct {
	// / (Optional) Requested page number, starting from 0 (defaults to 0 if not specified).
	//  (Deprecated) Use cursor-based pagination instead.
	PageNumber int32 `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"` // Deprecated: Do not use.
	// / (Required) Requested page size (if not specified, default size is operation specific).
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// / (Optional) The position in the collection from which the next page should be returned. If the cursor value is set, it is
	// always used, irrespective of the page number set.
	Cursor               string   `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{1}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (dst *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(dst, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *Page) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *Page) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Page) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

// / An entity representing pagination information returned to a client iterating over its elements.
// It includes current page that the client requested, and the total collection size.
// As not always pageCount * pageSize == itemCount, the item count is included as well.
type Pagination struct {
	// / (Required) Requested page details.
	CurrentPage *Page `protobuf:"bytes,1,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	// / Are there any more items to return? Use the cursor to fetch the next page when required.
	HasMore bool `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	// / (Deprecated) Use cursor-based pagination instead. Total number of pages.
	TotalPages int32 `protobuf:"varint,3,opt,name=totalPages,proto3" json:"totalPages,omitempty"` // Deprecated: Do not use.
	// / Total number of items.
	TotalItems int32 `protobuf:"varint,4,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	// / The last retrieved item's position in the collection. The cursor value can be sent on a subsequent request to
	// get the next page of items. Using cursors, instead of page numbers, will guarantee that all items are
	// retrieved with a potential of items being duplicated.
	Cursor string `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// / Position of the cursor relative to totalItems. It can be used to determine what pageNumber would overlap with a
	// cursor, or to provide an idea of progress when walking all pages. Valid values are [0, totalItems-1].
	CursorPosition       int32    `protobuf:"varint,6,opt,name=cursorPosition,proto3" json:"cursorPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{2}
}
func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (dst *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(dst, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetCurrentPage() *Page {
	if m != nil {
		return m.CurrentPage
	}
	return nil
}

func (m *Pagination) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

// Deprecated: Do not use.
func (m *Pagination) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *Pagination) GetTotalItems() int32 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *Pagination) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *Pagination) GetCursorPosition() int32 {
	if m != nil {
		return m.CursorPosition
	}
	return 0
}

// / Retry polices.
type RetryPolicy struct {
	// / (Required) Retry policy.
	//
	// Types that are valid to be assigned to Policy:
	//	*RetryPolicy_Immediate_
	//	*RetryPolicy_Delayed_
	//	*RetryPolicy_ExponentialBackOff_
	Policy               isRetryPolicy_Policy `protobuf_oneof:"Policy"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RetryPolicy) Reset()         { *m = RetryPolicy{} }
func (m *RetryPolicy) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy) ProtoMessage()    {}
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{3}
}
func (m *RetryPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryPolicy.Unmarshal(m, b)
}
func (m *RetryPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryPolicy.Marshal(b, m, deterministic)
}
func (dst *RetryPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy.Merge(dst, src)
}
func (m *RetryPolicy) XXX_Size() int {
	return xxx_messageInfo_RetryPolicy.Size(m)
}
func (m *RetryPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy proto.InternalMessageInfo

type isRetryPolicy_Policy interface {
	isRetryPolicy_Policy()
}

type RetryPolicy_Immediate_ struct {
	Immediate *RetryPolicy_Immediate `protobuf:"bytes,1,opt,name=immediate,proto3,oneof"`
}

type RetryPolicy_Delayed_ struct {
	Delayed *RetryPolicy_Delayed `protobuf:"bytes,2,opt,name=delayed,proto3,oneof"`
}

type RetryPolicy_ExponentialBackOff_ struct {
	ExponentialBackOff *RetryPolicy_ExponentialBackOff `protobuf:"bytes,3,opt,name=exponentialBackOff,proto3,oneof"`
}

func (*RetryPolicy_Immediate_) isRetryPolicy_Policy() {}

func (*RetryPolicy_Delayed_) isRetryPolicy_Policy() {}

func (*RetryPolicy_ExponentialBackOff_) isRetryPolicy_Policy() {}

func (m *RetryPolicy) GetPolicy() isRetryPolicy_Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *RetryPolicy) GetImmediate() *RetryPolicy_Immediate {
	if x, ok := m.GetPolicy().(*RetryPolicy_Immediate_); ok {
		return x.Immediate
	}
	return nil
}

func (m *RetryPolicy) GetDelayed() *RetryPolicy_Delayed {
	if x, ok := m.GetPolicy().(*RetryPolicy_Delayed_); ok {
		return x.Delayed
	}
	return nil
}

func (m *RetryPolicy) GetExponentialBackOff() *RetryPolicy_ExponentialBackOff {
	if x, ok := m.GetPolicy().(*RetryPolicy_ExponentialBackOff_); ok {
		return x.ExponentialBackOff
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RetryPolicy) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RetryPolicy_OneofMarshaler, _RetryPolicy_OneofUnmarshaler, _RetryPolicy_OneofSizer, []interface{}{
		(*RetryPolicy_Immediate_)(nil),
		(*RetryPolicy_Delayed_)(nil),
		(*RetryPolicy_ExponentialBackOff_)(nil),
	}
}

func _RetryPolicy_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RetryPolicy)
	// Policy
	switch x := m.Policy.(type) {
	case *RetryPolicy_Immediate_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Immediate); err != nil {
			return err
		}
	case *RetryPolicy_Delayed_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Delayed); err != nil {
			return err
		}
	case *RetryPolicy_ExponentialBackOff_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExponentialBackOff); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RetryPolicy.Policy has unexpected type %T", x)
	}
	return nil
}

func _RetryPolicy_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RetryPolicy)
	switch tag {
	case 1: // Policy.immediate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RetryPolicy_Immediate)
		err := b.DecodeMessage(msg)
		m.Policy = &RetryPolicy_Immediate_{msg}
		return true, err
	case 2: // Policy.delayed
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RetryPolicy_Delayed)
		err := b.DecodeMessage(msg)
		m.Policy = &RetryPolicy_Delayed_{msg}
		return true, err
	case 3: // Policy.exponentialBackOff
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RetryPolicy_ExponentialBackOff)
		err := b.DecodeMessage(msg)
		m.Policy = &RetryPolicy_ExponentialBackOff_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RetryPolicy_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RetryPolicy)
	// Policy
	switch x := m.Policy.(type) {
	case *RetryPolicy_Immediate_:
		s := proto.Size(x.Immediate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RetryPolicy_Delayed_:
		s := proto.Size(x.Delayed)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RetryPolicy_ExponentialBackOff_:
		s := proto.Size(x.ExponentialBackOff)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// / Re-run immediately.
type RetryPolicy_Immediate struct {
	// / Maximum number of retries.
	Retries              uint32   `protobuf:"varint,1,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryPolicy_Immediate) Reset()         { *m = RetryPolicy_Immediate{} }
func (m *RetryPolicy_Immediate) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy_Immediate) ProtoMessage()    {}
func (*RetryPolicy_Immediate) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{3, 0}
}
func (m *RetryPolicy_Immediate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryPolicy_Immediate.Unmarshal(m, b)
}
func (m *RetryPolicy_Immediate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryPolicy_Immediate.Marshal(b, m, deterministic)
}
func (dst *RetryPolicy_Immediate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy_Immediate.Merge(dst, src)
}
func (m *RetryPolicy_Immediate) XXX_Size() int {
	return xxx_messageInfo_RetryPolicy_Immediate.Size(m)
}
func (m *RetryPolicy_Immediate) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy_Immediate.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy_Immediate proto.InternalMessageInfo

func (m *RetryPolicy_Immediate) GetRetries() uint32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

// / Re-run after a given delay.
type RetryPolicy_Delayed struct {
	// / Initial delay in milliseconds.
	InitialDelayMs uint64 `protobuf:"varint,1,opt,name=initialDelayMs,proto3" json:"initialDelayMs,omitempty"`
	// / Subsequenet delays in milliseconds.
	DelayMs uint64 `protobuf:"varint,2,opt,name=delayMs,proto3" json:"delayMs,omitempty"`
	// / Maximum number of retries.
	Retries              uint32   `protobuf:"varint,3,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryPolicy_Delayed) Reset()         { *m = RetryPolicy_Delayed{} }
func (m *RetryPolicy_Delayed) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy_Delayed) ProtoMessage()    {}
func (*RetryPolicy_Delayed) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{3, 1}
}
func (m *RetryPolicy_Delayed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryPolicy_Delayed.Unmarshal(m, b)
}
func (m *RetryPolicy_Delayed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryPolicy_Delayed.Marshal(b, m, deterministic)
}
func (dst *RetryPolicy_Delayed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy_Delayed.Merge(dst, src)
}
func (m *RetryPolicy_Delayed) XXX_Size() int {
	return xxx_messageInfo_RetryPolicy_Delayed.Size(m)
}
func (m *RetryPolicy_Delayed) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy_Delayed.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy_Delayed proto.InternalMessageInfo

func (m *RetryPolicy_Delayed) GetInitialDelayMs() uint64 {
	if m != nil {
		return m.InitialDelayMs
	}
	return 0
}

func (m *RetryPolicy_Delayed) GetDelayMs() uint64 {
	if m != nil {
		return m.DelayMs
	}
	return 0
}

func (m *RetryPolicy_Delayed) GetRetries() uint32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

// / Exponential back-off retry policy.
type RetryPolicy_ExponentialBackOff struct {
	// / Initial delay in milliseconds.
	InitialDelayMs uint64 `protobuf:"varint,1,opt,name=initialDelayMs,proto3" json:"initialDelayMs,omitempty"`
	// / Upper bound on delay interval.
	MaxDelayIntervalMs uint64 `protobuf:"varint,2,opt,name=maxDelayIntervalMs,proto3" json:"maxDelayIntervalMs,omitempty"`
	// / Maximum number of retries.
	Retries              uint32   `protobuf:"varint,3,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryPolicy_ExponentialBackOff) Reset()         { *m = RetryPolicy_ExponentialBackOff{} }
func (m *RetryPolicy_ExponentialBackOff) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy_ExponentialBackOff) ProtoMessage()    {}
func (*RetryPolicy_ExponentialBackOff) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{3, 2}
}
func (m *RetryPolicy_ExponentialBackOff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryPolicy_ExponentialBackOff.Unmarshal(m, b)
}
func (m *RetryPolicy_ExponentialBackOff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryPolicy_ExponentialBackOff.Marshal(b, m, deterministic)
}
func (dst *RetryPolicy_ExponentialBackOff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy_ExponentialBackOff.Merge(dst, src)
}
func (m *RetryPolicy_ExponentialBackOff) XXX_Size() int {
	return xxx_messageInfo_RetryPolicy_ExponentialBackOff.Size(m)
}
func (m *RetryPolicy_ExponentialBackOff) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy_ExponentialBackOff.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy_ExponentialBackOff proto.InternalMessageInfo

func (m *RetryPolicy_ExponentialBackOff) GetInitialDelayMs() uint64 {
	if m != nil {
		return m.InitialDelayMs
	}
	return 0
}

func (m *RetryPolicy_ExponentialBackOff) GetMaxDelayIntervalMs() uint64 {
	if m != nil {
		return m.MaxDelayIntervalMs
	}
	return 0
}

func (m *RetryPolicy_ExponentialBackOff) GetRetries() uint32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

// / Token bucket policies
type TokenBucketPolicy struct {
	Capacity              uint64 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	InitialNumberOfTokens uint64 `protobuf:"varint,2,opt,name=initialNumberOfTokens,proto3" json:"initialNumberOfTokens,omitempty"`
	// Types that are valid to be assigned to RefillStrategy:
	//	*TokenBucketPolicy_FixedIntervalRefillStrategy_
	RefillStrategy       isTokenBucketPolicy_RefillStrategy `protobuf_oneof:"RefillStrategy"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *TokenBucketPolicy) Reset()         { *m = TokenBucketPolicy{} }
func (m *TokenBucketPolicy) String() string { return proto.CompactTextString(m) }
func (*TokenBucketPolicy) ProtoMessage()    {}
func (*TokenBucketPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{4}
}
func (m *TokenBucketPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenBucketPolicy.Unmarshal(m, b)
}
func (m *TokenBucketPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenBucketPolicy.Marshal(b, m, deterministic)
}
func (dst *TokenBucketPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenBucketPolicy.Merge(dst, src)
}
func (m *TokenBucketPolicy) XXX_Size() int {
	return xxx_messageInfo_TokenBucketPolicy.Size(m)
}
func (m *TokenBucketPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenBucketPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_TokenBucketPolicy proto.InternalMessageInfo

func (m *TokenBucketPolicy) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *TokenBucketPolicy) GetInitialNumberOfTokens() uint64 {
	if m != nil {
		return m.InitialNumberOfTokens
	}
	return 0
}

type isTokenBucketPolicy_RefillStrategy interface {
	isTokenBucketPolicy_RefillStrategy()
}

type TokenBucketPolicy_FixedIntervalRefillStrategy_ struct {
	FixedIntervalRefillStrategy *TokenBucketPolicy_FixedIntervalRefillStrategy `protobuf:"bytes,3,opt,name=fixedIntervalRefillStrategy,proto3,oneof"`
}

func (*TokenBucketPolicy_FixedIntervalRefillStrategy_) isTokenBucketPolicy_RefillStrategy() {}

func (m *TokenBucketPolicy) GetRefillStrategy() isTokenBucketPolicy_RefillStrategy {
	if m != nil {
		return m.RefillStrategy
	}
	return nil
}

func (m *TokenBucketPolicy) GetFixedIntervalRefillStrategy() *TokenBucketPolicy_FixedIntervalRefillStrategy {
	if x, ok := m.GetRefillStrategy().(*TokenBucketPolicy_FixedIntervalRefillStrategy_); ok {
		return x.FixedIntervalRefillStrategy
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TokenBucketPolicy) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TokenBucketPolicy_OneofMarshaler, _TokenBucketPolicy_OneofUnmarshaler, _TokenBucketPolicy_OneofSizer, []interface{}{
		(*TokenBucketPolicy_FixedIntervalRefillStrategy_)(nil),
	}
}

func _TokenBucketPolicy_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TokenBucketPolicy)
	// RefillStrategy
	switch x := m.RefillStrategy.(type) {
	case *TokenBucketPolicy_FixedIntervalRefillStrategy_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FixedIntervalRefillStrategy); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TokenBucketPolicy.RefillStrategy has unexpected type %T", x)
	}
	return nil
}

func _TokenBucketPolicy_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TokenBucketPolicy)
	switch tag {
	case 3: // RefillStrategy.fixedIntervalRefillStrategy
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TokenBucketPolicy_FixedIntervalRefillStrategy)
		err := b.DecodeMessage(msg)
		m.RefillStrategy = &TokenBucketPolicy_FixedIntervalRefillStrategy_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TokenBucketPolicy_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TokenBucketPolicy)
	// RefillStrategy
	switch x := m.RefillStrategy.(type) {
	case *TokenBucketPolicy_FixedIntervalRefillStrategy_:
		s := proto.Size(x.FixedIntervalRefillStrategy)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TokenBucketPolicy_FixedIntervalRefillStrategy struct {
	RefillRate           uint64   `protobuf:"varint,3,opt,name=refillRate,proto3" json:"refillRate,omitempty"`
	IntervalMs           uint64   `protobuf:"varint,4,opt,name=intervalMs,proto3" json:"intervalMs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) Reset() {
	*m = TokenBucketPolicy_FixedIntervalRefillStrategy{}
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) String() string {
	return proto.CompactTextString(m)
}
func (*TokenBucketPolicy_FixedIntervalRefillStrategy) ProtoMessage() {}
func (*TokenBucketPolicy_FixedIntervalRefillStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{4, 0}
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.Unmarshal(m, b)
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.Marshal(b, m, deterministic)
}
func (dst *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.Merge(dst, src)
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_Size() int {
	return xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.Size(m)
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy proto.InternalMessageInfo

func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) GetRefillRate() uint64 {
	if m != nil {
		return m.RefillRate
	}
	return 0
}

func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) GetIntervalMs() uint64 {
	if m != nil {
		return m.IntervalMs
	}
	return 0
}

// / A reference to an entity in the Titus hierarchy.
type Reference struct {
	// Types that are valid to be assigned to Reference:
	//	*Reference_System_
	//	*Reference_Tier
	//	*Reference_CapacityGroup
	//	*Reference_JobId
	//	*Reference_TaskId
	Reference            isReference_Reference `protobuf_oneof:"Reference"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Reference) Reset()         { *m = Reference{} }
func (m *Reference) String() string { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()    {}
func (*Reference) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{5}
}
func (m *Reference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference.Unmarshal(m, b)
}
func (m *Reference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference.Marshal(b, m, deterministic)
}
func (dst *Reference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference.Merge(dst, src)
}
func (m *Reference) XXX_Size() int {
	return xxx_messageInfo_Reference.Size(m)
}
func (m *Reference) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference.DiscardUnknown(m)
}

var xxx_messageInfo_Reference proto.InternalMessageInfo

type isReference_Reference interface {
	isReference_Reference()
}

type Reference_System_ struct {
	System *Reference_System `protobuf:"bytes,1,opt,name=system,proto3,oneof"`
}

type Reference_Tier struct {
	Tier Tier `protobuf:"varint,2,opt,name=tier,proto3,enum=com.netflix.titus.Tier,oneof"`
}

type Reference_CapacityGroup struct {
	CapacityGroup string `protobuf:"bytes,3,opt,name=capacityGroup,proto3,oneof"`
}

type Reference_JobId struct {
	JobId string `protobuf:"bytes,4,opt,name=jobId,proto3,oneof"`
}

type Reference_TaskId struct {
	TaskId string `protobuf:"bytes,5,opt,name=taskId,proto3,oneof"`
}

func (*Reference_System_) isReference_Reference() {}

func (*Reference_Tier) isReference_Reference() {}

func (*Reference_CapacityGroup) isReference_Reference() {}

func (*Reference_JobId) isReference_Reference() {}

func (*Reference_TaskId) isReference_Reference() {}

func (m *Reference) GetReference() isReference_Reference {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *Reference) GetSystem() *Reference_System {
	if x, ok := m.GetReference().(*Reference_System_); ok {
		return x.System
	}
	return nil
}

func (m *Reference) GetTier() Tier {
	if x, ok := m.GetReference().(*Reference_Tier); ok {
		return x.Tier
	}
	return Tier_Flex
}

func (m *Reference) GetCapacityGroup() string {
	if x, ok := m.GetReference().(*Reference_CapacityGroup); ok {
		return x.CapacityGroup
	}
	return ""
}

func (m *Reference) GetJobId() string {
	if x, ok := m.GetReference().(*Reference_JobId); ok {
		return x.JobId
	}
	return ""
}

func (m *Reference) GetTaskId() string {
	if x, ok := m.GetReference().(*Reference_TaskId); ok {
		return x.TaskId
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Reference) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Reference_OneofMarshaler, _Reference_OneofUnmarshaler, _Reference_OneofSizer, []interface{}{
		(*Reference_System_)(nil),
		(*Reference_Tier)(nil),
		(*Reference_CapacityGroup)(nil),
		(*Reference_JobId)(nil),
		(*Reference_TaskId)(nil),
	}
}

func _Reference_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Reference)
	// Reference
	switch x := m.Reference.(type) {
	case *Reference_System_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.System); err != nil {
			return err
		}
	case *Reference_Tier:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Tier))
	case *Reference_CapacityGroup:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.CapacityGroup)
	case *Reference_JobId:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.JobId)
	case *Reference_TaskId:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.TaskId)
	case nil:
	default:
		return fmt.Errorf("Reference.Reference has unexpected type %T", x)
	}
	return nil
}

func _Reference_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Reference)
	switch tag {
	case 1: // Reference.system
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Reference_System)
		err := b.DecodeMessage(msg)
		m.Reference = &Reference_System_{msg}
		return true, err
	case 2: // Reference.tier
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Reference = &Reference_Tier{Tier(x)}
		return true, err
	case 3: // Reference.capacityGroup
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Reference = &Reference_CapacityGroup{x}
		return true, err
	case 4: // Reference.jobId
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Reference = &Reference_JobId{x}
		return true, err
	case 5: // Reference.taskId
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Reference = &Reference_TaskId{x}
		return true, err
	default:
		return false, nil
	}
}

func _Reference_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Reference)
	// Reference
	switch x := m.Reference.(type) {
	case *Reference_System_:
		s := proto.Size(x.System)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Reference_Tier:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Tier))
	case *Reference_CapacityGroup:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CapacityGroup)))
		n += len(x.CapacityGroup)
	case *Reference_JobId:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.JobId)))
		n += len(x.JobId)
	case *Reference_TaskId:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.TaskId)))
		n += len(x.TaskId)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Reference_System struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reference_System) Reset()         { *m = Reference_System{} }
func (m *Reference_System) String() string { return proto.CompactTextString(m) }
func (*Reference_System) ProtoMessage()    {}
func (*Reference_System) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{5, 0}
}
func (m *Reference_System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference_System.Unmarshal(m, b)
}
func (m *Reference_System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference_System.Marshal(b, m, deterministic)
}
func (dst *Reference_System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference_System.Merge(dst, src)
}
func (m *Reference_System) XXX_Size() int {
	return xxx_messageInfo_Reference_System.Size(m)
}
func (m *Reference_System) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference_System.DiscardUnknown(m)
}

var xxx_messageInfo_Reference_System proto.InternalMessageInfo

// / Instance resource dimensions
type ResourceDimension struct {
	Cpu                  uint32   `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu                  uint32   `protobuf:"varint,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	MemoryMB             uint32   `protobuf:"varint,3,opt,name=memoryMB,proto3" json:"memoryMB,omitempty"`
	DiskMB               uint32   `protobuf:"varint,4,opt,name=diskMB,proto3" json:"diskMB,omitempty"`
	NetworkMbps          uint32   `protobuf:"varint,5,opt,name=networkMbps,proto3" json:"networkMbps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceDimension) Reset()         { *m = ResourceDimension{} }
func (m *ResourceDimension) String() string { return proto.CompactTextString(m) }
func (*ResourceDimension) ProtoMessage()    {}
func (*ResourceDimension) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{6}
}
func (m *ResourceDimension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceDimension.Unmarshal(m, b)
}
func (m *ResourceDimension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceDimension.Marshal(b, m, deterministic)
}
func (dst *ResourceDimension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceDimension.Merge(dst, src)
}
func (m *ResourceDimension) XXX_Size() int {
	return xxx_messageInfo_ResourceDimension.Size(m)
}
func (m *ResourceDimension) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceDimension.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceDimension proto.InternalMessageInfo

func (m *ResourceDimension) GetCpu() uint32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *ResourceDimension) GetGpu() uint32 {
	if m != nil {
		return m.Gpu
	}
	return 0
}

func (m *ResourceDimension) GetMemoryMB() uint32 {
	if m != nil {
		return m.MemoryMB
	}
	return 0
}

func (m *ResourceDimension) GetDiskMB() uint32 {
	if m != nil {
		return m.DiskMB
	}
	return 0
}

func (m *ResourceDimension) GetNetworkMbps() uint32 {
	if m != nil {
		return m.NetworkMbps
	}
	return 0
}

// / Time window descriptor.
type TimeWindow struct {
	// / (Required) Included days.
	Days []Day `protobuf:"varint,1,rep,packed,name=days,proto3,enum=com.netflix.titus.Day" json:"days,omitempty"`
	// / (Optional) Included hour ranges. If not set, defaults to 0-24.
	HourlyTimeWindows []*TimeWindow_HourlyTimeWindow `protobuf:"bytes,2,rep,name=hourlyTimeWindows,proto3" json:"hourlyTimeWindows,omitempty"`
	// / (Optional) If not set, UTC time zone is set as a default.
	TimeZone             string   `protobuf:"bytes,3,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeWindow) Reset()         { *m = TimeWindow{} }
func (m *TimeWindow) String() string { return proto.CompactTextString(m) }
func (*TimeWindow) ProtoMessage()    {}
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{7}
}
func (m *TimeWindow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeWindow.Unmarshal(m, b)
}
func (m *TimeWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeWindow.Marshal(b, m, deterministic)
}
func (dst *TimeWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeWindow.Merge(dst, src)
}
func (m *TimeWindow) XXX_Size() int {
	return xxx_messageInfo_TimeWindow.Size(m)
}
func (m *TimeWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeWindow.DiscardUnknown(m)
}

var xxx_messageInfo_TimeWindow proto.InternalMessageInfo

func (m *TimeWindow) GetDays() []Day {
	if m != nil {
		return m.Days
	}
	return nil
}

func (m *TimeWindow) GetHourlyTimeWindows() []*TimeWindow_HourlyTimeWindow {
	if m != nil {
		return m.HourlyTimeWindows
	}
	return nil
}

func (m *TimeWindow) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

type TimeWindow_HourlyTimeWindow struct {
	// / (Required) Starting hour.
	StartHour uint32 `protobuf:"varint,1,opt,name=startHour,proto3" json:"startHour,omitempty"`
	// / (Required) Ending hour.
	EndHour              uint32   `protobuf:"varint,2,opt,name=endHour,proto3" json:"endHour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeWindow_HourlyTimeWindow) Reset()         { *m = TimeWindow_HourlyTimeWindow{} }
func (m *TimeWindow_HourlyTimeWindow) String() string { return proto.CompactTextString(m) }
func (*TimeWindow_HourlyTimeWindow) ProtoMessage()    {}
func (*TimeWindow_HourlyTimeWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{7, 0}
}
func (m *TimeWindow_HourlyTimeWindow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeWindow_HourlyTimeWindow.Unmarshal(m, b)
}
func (m *TimeWindow_HourlyTimeWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeWindow_HourlyTimeWindow.Marshal(b, m, deterministic)
}
func (dst *TimeWindow_HourlyTimeWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeWindow_HourlyTimeWindow.Merge(dst, src)
}
func (m *TimeWindow_HourlyTimeWindow) XXX_Size() int {
	return xxx_messageInfo_TimeWindow_HourlyTimeWindow.Size(m)
}
func (m *TimeWindow_HourlyTimeWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeWindow_HourlyTimeWindow.DiscardUnknown(m)
}

var xxx_messageInfo_TimeWindow_HourlyTimeWindow proto.InternalMessageInfo

func (m *TimeWindow_HourlyTimeWindow) GetStartHour() uint32 {
	if m != nil {
		return m.StartHour
	}
	return 0
}

func (m *TimeWindow_HourlyTimeWindow) GetEndHour() uint32 {
	if m != nil {
		return m.EndHour
	}
	return 0
}

// / A provider for container health
type ContainerHealthProvider struct {
	// / (Required) The name of the provider.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// / (Optional) Attributes to be used by the provider.
	Attributes           map[string]string `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ContainerHealthProvider) Reset()         { *m = ContainerHealthProvider{} }
func (m *ContainerHealthProvider) String() string { return proto.CompactTextString(m) }
func (*ContainerHealthProvider) ProtoMessage()    {}
func (*ContainerHealthProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_base_0e64b913222b7f16, []int{8}
}
func (m *ContainerHealthProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerHealthProvider.Unmarshal(m, b)
}
func (m *ContainerHealthProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerHealthProvider.Marshal(b, m, deterministic)
}
func (dst *ContainerHealthProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerHealthProvider.Merge(dst, src)
}
func (m *ContainerHealthProvider) XXX_Size() int {
	return xxx_messageInfo_ContainerHealthProvider.Size(m)
}
func (m *ContainerHealthProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerHealthProvider.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerHealthProvider proto.InternalMessageInfo

func (m *ContainerHealthProvider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainerHealthProvider) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*CallMetadata)(nil), "com.netflix.titus.CallMetadata")
	proto.RegisterType((*Page)(nil), "com.netflix.titus.Page")
	proto.RegisterType((*Pagination)(nil), "com.netflix.titus.Pagination")
	proto.RegisterType((*RetryPolicy)(nil), "com.netflix.titus.RetryPolicy")
	proto.RegisterType((*RetryPolicy_Immediate)(nil), "com.netflix.titus.RetryPolicy.Immediate")
	proto.RegisterType((*RetryPolicy_Delayed)(nil), "com.netflix.titus.RetryPolicy.Delayed")
	proto.RegisterType((*RetryPolicy_ExponentialBackOff)(nil), "com.netflix.titus.RetryPolicy.ExponentialBackOff")
	proto.RegisterType((*TokenBucketPolicy)(nil), "com.netflix.titus.TokenBucketPolicy")
	proto.RegisterType((*TokenBucketPolicy_FixedIntervalRefillStrategy)(nil), "com.netflix.titus.TokenBucketPolicy.FixedIntervalRefillStrategy")
	proto.RegisterType((*Reference)(nil), "com.netflix.titus.Reference")
	proto.RegisterType((*Reference_System)(nil), "com.netflix.titus.Reference.System")
	proto.RegisterType((*ResourceDimension)(nil), "com.netflix.titus.ResourceDimension")
	proto.RegisterType((*TimeWindow)(nil), "com.netflix.titus.TimeWindow")
	proto.RegisterType((*TimeWindow_HourlyTimeWindow)(nil), "com.netflix.titus.TimeWindow.HourlyTimeWindow")
	proto.RegisterType((*ContainerHealthProvider)(nil), "com.netflix.titus.ContainerHealthProvider")
	proto.RegisterMapType((map[string]string)(nil), "com.netflix.titus.ContainerHealthProvider.AttributesEntry")
	proto.RegisterEnum("com.netflix.titus.Tier", Tier_name, Tier_value)
	proto.RegisterEnum("com.netflix.titus.Level", Level_name, Level_value)
	proto.RegisterEnum("com.netflix.titus.MountPerm", MountPerm_name, MountPerm_value)
	proto.RegisterEnum("com.netflix.titus.Day", Day_name, Day_value)
}

func init() {
	proto.RegisterFile("netflix/titus/titus_base.proto", fileDescriptor_titus_base_0e64b913222b7f16)
}

var fileDescriptor_titus_base_0e64b913222b7f16 = []byte{
	// 1170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0xf7, 0xfa, 0x2b, 0xf6, 0x71, 0x93, 0x3a, 0xa3, 0xff, 0x3f, 0x35, 0x2e, 0x2a, 0x91, 0x2b,
	0xaa, 0x28, 0x12, 0xae, 0x08, 0x20, 0x41, 0xa5, 0x4a, 0xe0, 0xa4, 0xc5, 0xa9, 0x30, 0xb1, 0x26,
	0x91, 0x22, 0x55, 0x05, 0x34, 0xde, 0x3d, 0x76, 0x06, 0xef, 0xce, 0x58, 0xb3, 0xb3, 0x69, 0x16,
	0x71, 0x89, 0xb8, 0xe3, 0x21, 0x78, 0x1b, 0x5e, 0x82, 0x4b, 0x6e, 0x78, 0x08, 0x84, 0x66, 0x66,
	0xd7, 0xd9, 0xc6, 0x4e, 0xcb, 0x4d, 0x32, 0xbf, 0xf3, 0xf9, 0x3b, 0x67, 0xce, 0x19, 0x2f, 0x3c,
	0x10, 0xa8, 0xa7, 0x21, 0xbf, 0x7a, 0xac, 0xb9, 0x4e, 0x62, 0xf7, 0xf7, 0x87, 0x09, 0x8b, 0xb1,
	0xbf, 0x50, 0x52, 0x4b, 0xb2, 0xed, 0xcb, 0xa8, 0x9f, 0xd9, 0xf4, 0xad, 0xb6, 0xfb, 0xde, 0x4c,
	0xca, 0x59, 0x88, 0x8f, 0xad, 0xc1, 0x24, 0x99, 0x3e, 0x66, 0x22, 0x75, 0xd6, 0xbd, 0x9f, 0xe1,
	0xce, 0x21, 0x0b, 0xc3, 0x11, 0x6a, 0x16, 0x30, 0xcd, 0x48, 0x17, 0x1a, 0x3e, 0x0b, 0x43, 0x54,
	0xc7, 0x41, 0xc7, 0xdb, 0xf5, 0xf6, 0x9a, 0x74, 0x89, 0xc9, 0x03, 0x00, 0x73, 0xa6, 0xc8, 0x62,
	0x29, 0x3a, 0x65, 0xab, 0x2d, 0x48, 0x72, 0xdf, 0x31, 0xd3, 0x17, 0x9d, 0xca, 0x6e, 0x25, 0xf7,
	0x35, 0x98, 0xfc, 0x0f, 0x6a, 0x01, 0x4e, 0x92, 0x59, 0xa7, 0xba, 0xeb, 0xed, 0x35, 0xa8, 0x03,
	0xbd, 0xef, 0xa1, 0x3a, 0x66, 0x33, 0x24, 0x3d, 0x80, 0x05, 0x9b, 0xe1, 0xb7, 0x49, 0x34, 0x41,
	0x65, 0xf3, 0xd6, 0x06, 0xe5, 0x8e, 0x47, 0x0b, 0x52, 0x13, 0xdd, 0xa0, 0x53, 0xfe, 0x13, 0xda,
	0xdc, 0x35, 0xba, 0xc4, 0x64, 0x07, 0xea, 0x7e, 0xa2, 0x62, 0xa9, 0x3a, 0x15, 0xcb, 0x2a, 0x43,
	0xbd, 0xbf, 0x3c, 0x80, 0x31, 0x9b, 0x71, 0xc1, 0x34, 0x97, 0x82, 0x7c, 0x01, 0x2d, 0x3f, 0x51,
	0x0a, 0x85, 0x36, 0x59, 0x6d, 0x9e, 0xd6, 0xc1, 0xbd, 0xfe, 0x4a, 0xc3, 0xfa, 0x46, 0x4d, 0x8b,
	0xb6, 0xa4, 0x03, 0x1b, 0x17, 0x2c, 0x1e, 0x49, 0xe5, 0x92, 0x37, 0x68, 0x0e, 0x0d, 0x77, 0x2d,
	0x35, 0x0b, 0x8d, 0x59, 0x6c, 0xf3, 0x67, 0xdc, 0xaf, 0xa5, 0xa6, 0x73, 0x16, 0x1d, 0x6b, 0x8c,
	0x62, 0xdb, 0x82, 0x1a, 0x2d, 0x48, 0x0a, 0xfc, 0x6b, 0x45, 0xfe, 0xe4, 0x11, 0x6c, 0xb9, 0xd3,
	0x58, 0xc6, 0xdc, 0x94, 0xd0, 0xa9, 0x5b, 0xdf, 0x1b, 0xd2, 0xde, 0xef, 0x55, 0x68, 0x51, 0xd4,
	0x2a, 0x1d, 0xcb, 0x90, 0xfb, 0x29, 0x19, 0x42, 0x93, 0x47, 0x11, 0x06, 0x9c, 0xe9, 0xbc, 0xcc,
	0xbd, 0x35, 0x65, 0x16, 0x5c, 0xfa, 0xc7, 0xb9, 0xfd, 0xb0, 0x44, 0xaf, 0x9d, 0xc9, 0x00, 0x36,
	0x02, 0x0c, 0x59, 0x8a, 0x81, 0xad, 0xbb, 0x75, 0xf0, 0xe8, 0x1d, 0x71, 0x8e, 0x9c, 0xf5, 0xb0,
	0x44, 0x73, 0x47, 0xe2, 0x03, 0xc1, 0xab, 0x85, 0x14, 0x28, 0x34, 0x67, 0xe1, 0x80, 0xf9, 0xf3,
	0x93, 0xe9, 0xd4, 0x76, 0xaa, 0x75, 0xf0, 0xf1, 0x3b, 0xc2, 0x3d, 0x5b, 0x71, 0x1c, 0x96, 0xe8,
	0x9a, 0x70, 0xdd, 0x0f, 0xa1, 0xb9, 0x2c, 0xc1, 0xdc, 0x96, 0x42, 0xad, 0x38, 0xc6, 0xb6, 0xfa,
	0x4d, 0x9a, 0xc3, 0x2e, 0xc2, 0x46, 0xc6, 0xd0, 0x34, 0x97, 0x0b, 0x6e, 0x62, 0x58, 0xc9, 0xc8,
	0xd9, 0x56, 0xe9, 0x0d, 0xa9, 0x09, 0x16, 0x64, 0x06, 0x65, 0x6b, 0x90, 0xc3, 0x62, 0x9a, 0xca,
	0x9b, 0x69, 0x7e, 0xf5, 0x80, 0xac, 0x52, 0xff, 0xcf, 0x29, 0xfb, 0x40, 0x22, 0x76, 0x65, 0xd1,
	0xb1, 0xd0, 0xa8, 0x2e, 0x59, 0xb8, 0xcc, 0xbe, 0x46, 0x73, 0x3b, 0x91, 0x41, 0x03, 0xea, 0xae,
	0x93, 0xbd, 0x3f, 0xcb, 0xb0, 0x7d, 0x26, 0xe7, 0x28, 0x06, 0x89, 0x3f, 0x47, 0x9d, 0x4d, 0x8a,
	0xdd, 0xd9, 0x05, 0xf3, 0xb9, 0x4e, 0x33, 0x2e, 0x4b, 0x4c, 0x3e, 0x85, 0xff, 0x67, 0xbc, 0xdc,
	0x0a, 0x9e, 0x4c, 0xad, 0x7f, 0x4e, 0x64, 0xbd, 0x92, 0xfc, 0xe2, 0xc1, 0xfd, 0x29, 0xbf, 0xc2,
	0x20, 0xe7, 0x47, 0x71, 0xca, 0xc3, 0xf0, 0x54, 0x2b, 0xa6, 0x71, 0x96, 0x66, 0xf7, 0xfe, 0xe5,
	0x9a, 0x7b, 0x5f, 0x61, 0xd7, 0x7f, 0x7e, 0x7b, 0x9c, 0x61, 0x89, 0xbe, 0x2d, 0x4d, 0xf7, 0x3b,
	0xb8, 0xff, 0x16, 0x6f, 0xb3, 0x91, 0xca, 0x4a, 0xa8, 0x59, 0x91, 0x8a, 0x2d, 0xa8, 0x20, 0x31,
	0x7a, 0x7e, 0xdd, 0xf9, 0xaa, 0xd3, 0x5f, 0x4b, 0x06, 0x6d, 0xd8, 0x7a, 0x33, 0x62, 0xef, 0x6f,
	0x0f, 0x9a, 0x14, 0xa7, 0xa8, 0x50, 0xf8, 0x48, 0x9e, 0x42, 0x3d, 0x4e, 0x63, 0x8d, 0x51, 0xb6,
	0x7e, 0x0f, 0xd7, 0xce, 0x79, 0x66, 0xdd, 0x3f, 0xb5, 0xa6, 0xc3, 0x12, 0xcd, 0x9c, 0xc8, 0x47,
	0x50, 0xd5, 0x1c, 0x95, 0xed, 0xf4, 0xd6, 0xda, 0x27, 0xea, 0x8c, 0xa3, 0x1a, 0x96, 0xa8, 0x35,
	0x23, 0x8f, 0x60, 0x33, 0xbf, 0xb5, 0xaf, 0x95, 0x4c, 0x16, 0xee, 0x19, 0x1c, 0x96, 0xe8, 0x9b,
	0x62, 0xb2, 0x03, 0xb5, 0x1f, 0xe5, 0xe4, 0x38, 0xb0, 0x05, 0x19, 0xbd, 0x83, 0xa4, 0x03, 0x75,
	0xcd, 0xe2, 0xf9, 0x71, 0xe0, 0xde, 0x1f, 0x43, 0xc4, 0xe1, 0x6e, 0x03, 0xea, 0x8e, 0xdc, 0xa0,
	0x55, 0x28, 0xaf, 0xf7, 0x9b, 0x07, 0xdb, 0x14, 0x63, 0x99, 0x28, 0x1f, 0x8f, 0x78, 0x84, 0x22,
	0x36, 0xef, 0x6b, 0x1b, 0x2a, 0xfe, 0x22, 0xc9, 0x56, 0xce, 0x1c, 0x8d, 0x64, 0xb6, 0x48, 0x6c,
	0x19, 0x9b, 0xd4, 0x1c, 0xcd, 0xc0, 0x45, 0x18, 0x49, 0x95, 0x8e, 0x06, 0xd9, 0xac, 0x2e, 0xb1,
	0x79, 0x06, 0x03, 0x1e, 0xcf, 0x47, 0x03, 0xcb, 0x6f, 0x93, 0x66, 0x88, 0xec, 0x42, 0x4b, 0xa0,
	0x7e, 0x2d, 0xd5, 0x7c, 0x34, 0x59, 0xc4, 0x96, 0xe3, 0x26, 0x2d, 0x8a, 0x7a, 0xff, 0x78, 0x00,
	0x67, 0x3c, 0xc2, 0x73, 0x2e, 0x02, 0xf9, 0x9a, 0xec, 0x43, 0x35, 0x60, 0xa9, 0xd9, 0xae, 0xca,
	0xde, 0xd6, 0xc1, 0xce, 0x9a, 0xf6, 0x1d, 0xb1, 0x94, 0x5a, 0x1b, 0xf2, 0x0a, 0xb6, 0x2f, 0x64,
	0xa2, 0xc2, 0xf4, 0xda, 0xdf, 0x4c, 0x78, 0x65, 0xaf, 0x75, 0xd0, 0x5f, 0xdb, 0xf7, 0xdc, 0xaa,
	0x3f, 0xbc, 0xe1, 0x46, 0x57, 0x03, 0x99, 0x72, 0x35, 0x8f, 0xf0, 0xa5, 0x14, 0x98, 0xfd, 0x36,
	0x2d, 0x71, 0xf7, 0x05, 0xb4, 0x6f, 0x86, 0x20, 0xef, 0x43, 0x33, 0xd6, 0x4c, 0x69, 0xa3, 0xc8,
	0x1a, 0x79, 0x2d, 0x30, 0x7b, 0x8e, 0x22, 0xb0, 0x3a, 0xd7, 0xd2, 0x1c, 0xf6, 0xfe, 0xf0, 0xe0,
	0xde, 0xa1, 0x14, 0x9a, 0x71, 0x81, 0x6a, 0x88, 0x2c, 0xd4, 0x17, 0x63, 0x25, 0x2f, 0x79, 0x80,
	0x8a, 0x10, 0xa8, 0x0a, 0x16, 0x61, 0xf6, 0x7b, 0x6e, 0xcf, 0xe4, 0x25, 0x00, 0xd3, 0x5a, 0xf1,
	0x49, 0xa2, 0xed, 0xa3, 0x61, 0xca, 0x7d, 0xb2, 0xa6, 0xdc, 0x5b, 0x62, 0xf6, 0xbf, 0x5a, 0x3a,
	0x3f, 0x13, 0x5a, 0xa5, 0xb4, 0x10, 0xad, 0xfb, 0x14, 0xee, 0xde, 0x50, 0x9b, 0x39, 0x98, 0x63,
	0x9a, 0x31, 0x30, 0x47, 0xf3, 0x41, 0x70, 0xc9, 0xc2, 0x04, 0xb3, 0xef, 0x08, 0x07, 0x9e, 0x94,
	0x3f, 0xf7, 0xf6, 0x1f, 0x40, 0xd5, 0x0c, 0x37, 0x69, 0x40, 0xf5, 0x79, 0x88, 0x57, 0xed, 0x12,
	0xb9, 0x03, 0x8d, 0x43, 0xc5, 0x35, 0xf7, 0x59, 0xd8, 0xf6, 0xf6, 0x5f, 0x41, 0xed, 0x1b, 0xbc,
	0xc4, 0x90, 0xdc, 0x85, 0x96, 0x9b, 0x4d, 0x0b, 0xdb, 0x25, 0xb2, 0x09, 0x4d, 0xe3, 0xe9, 0xa0,
	0x47, 0x76, 0x80, 0x1c, 0x16, 0xc7, 0xdf, 0xc9, 0xcb, 0x26, 0xdc, 0x0b, 0x39, 0x71, 0xa8, 0x62,
	0x9d, 0x58, 0x3c, 0x77, 0xb0, 0xba, 0xff, 0x10, 0x9a, 0x23, 0x99, 0x08, 0x3d, 0x46, 0x15, 0x91,
	0x3a, 0x94, 0xe9, 0x49, 0xbb, 0x64, 0xfe, 0x9f, 0x9f, 0xb4, 0x3d, 0x8b, 0xcf, 0xdb, 0xe5, 0x7d,
	0x06, 0x95, 0x23, 0x96, 0x12, 0x80, 0xfa, 0x48, 0x8a, 0x80, 0xa5, 0xed, 0x12, 0x69, 0xc1, 0xc6,
	0x59, 0x82, 0xb1, 0x01, 0x9e, 0x89, 0x79, 0x8e, 0x81, 0x70, 0xd0, 0x26, 0x3c, 0xbb, 0x48, 0x94,
	0x45, 0x15, 0xe3, 0xf5, 0x5c, 0x71, 0x73, 0xae, 0x1a, 0xcd, 0x29, 0xd3, 0x89, 0x32, 0xa8, 0x66,
	0x34, 0xa7, 0x89, 0x8d, 0x57, 0x1f, 0x7c, 0x06, 0x1f, 0xac, 0xde, 0xc6, 0x4c, 0x2d, 0x7c, 0xf7,
	0xe1, 0x36, 0x43, 0x31, 0x68, 0x9e, 0x19, 0xe1, 0x80, 0xc5, 0x38, 0xf6, 0x5e, 0xd6, 0xac, 0xc5,
	0xa4, 0x6e, 0xb5, 0x9f, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x3a, 0xe7, 0x3d, 0x26, 0x0a,
	0x00, 0x00,
}
