// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netflix/titus/titus_vpc_api.proto

package titus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Family int32

const (
	// Default should never really be used, but we're required to have one due to protobuf
	Family_FAMILY_DEFAULT Family = 0
	Family_FAMILY_V4      Family = 1
	Family_FAMILY_V6      Family = 2
)

var Family_name = map[int32]string{
	0: "FAMILY_DEFAULT",
	1: "FAMILY_V4",
	2: "FAMILY_V6",
}
var Family_value = map[string]int32{
	"FAMILY_DEFAULT": 0,
	"FAMILY_V4":      1,
	"FAMILY_V6":      2,
}

func (x Family) String() string {
	return proto.EnumName(Family_name, int32(x))
}
func (Family) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_titus_vpc_api_287c2149623615e8, []int{0}
}

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_vpc_api_287c2149623615e8, []int{0}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AddressLocation struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	AvailabilityZone     string   `protobuf:"bytes,2,opt,name=availabilityZone,proto3" json:"availabilityZone,omitempty"`
	SubnetId             string   `protobuf:"bytes,3,opt,name=subnetId,proto3" json:"subnetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressLocation) Reset()         { *m = AddressLocation{} }
func (m *AddressLocation) String() string { return proto.CompactTextString(m) }
func (*AddressLocation) ProtoMessage()    {}
func (*AddressLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_vpc_api_287c2149623615e8, []int{1}
}
func (m *AddressLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressLocation.Unmarshal(m, b)
}
func (m *AddressLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressLocation.Marshal(b, m, deterministic)
}
func (dst *AddressLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressLocation.Merge(dst, src)
}
func (m *AddressLocation) XXX_Size() int {
	return xxx_messageInfo_AddressLocation.Size(m)
}
func (m *AddressLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressLocation.DiscardUnknown(m)
}

var xxx_messageInfo_AddressLocation proto.InternalMessageInfo

func (m *AddressLocation) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *AddressLocation) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

func (m *AddressLocation) GetSubnetId() string {
	if m != nil {
		return m.SubnetId
	}
	return ""
}

type AddressAllocation struct {
	AddressLocation *AddressLocation `protobuf:"bytes,1,opt,name=addressLocation,proto3" json:"addressLocation,omitempty"`
	// A valid UUID4. It should be set during allocation, if unset, one will be set for you.
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// address.address must be unset when requesting an allocation
	Address              *Address `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressAllocation) Reset()         { *m = AddressAllocation{} }
func (m *AddressAllocation) String() string { return proto.CompactTextString(m) }
func (*AddressAllocation) ProtoMessage()    {}
func (*AddressAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_vpc_api_287c2149623615e8, []int{2}
}
func (m *AddressAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressAllocation.Unmarshal(m, b)
}
func (m *AddressAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressAllocation.Marshal(b, m, deterministic)
}
func (dst *AddressAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressAllocation.Merge(dst, src)
}
func (m *AddressAllocation) XXX_Size() int {
	return xxx_messageInfo_AddressAllocation.Size(m)
}
func (m *AddressAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_AddressAllocation proto.InternalMessageInfo

func (m *AddressAllocation) GetAddressLocation() *AddressLocation {
	if m != nil {
		return m.AddressLocation
	}
	return nil
}

func (m *AddressAllocation) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddressAllocation) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type SignedAddressAllocation struct {
	AddressAllocation *AddressAllocation `protobuf:"bytes,1,opt,name=addressAllocation,proto3" json:"addressAllocation,omitempty"`
	// This is an x509v3 signed version of the Address allocation.
	SignedAddressAllocation []byte   `protobuf:"bytes,2,opt,name=signedAddressAllocation,proto3" json:"signedAddressAllocation,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *SignedAddressAllocation) Reset()         { *m = SignedAddressAllocation{} }
func (m *SignedAddressAllocation) String() string { return proto.CompactTextString(m) }
func (*SignedAddressAllocation) ProtoMessage()    {}
func (*SignedAddressAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_vpc_api_287c2149623615e8, []int{3}
}
func (m *SignedAddressAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedAddressAllocation.Unmarshal(m, b)
}
func (m *SignedAddressAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedAddressAllocation.Marshal(b, m, deterministic)
}
func (dst *SignedAddressAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedAddressAllocation.Merge(dst, src)
}
func (m *SignedAddressAllocation) XXX_Size() int {
	return xxx_messageInfo_SignedAddressAllocation.Size(m)
}
func (m *SignedAddressAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedAddressAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_SignedAddressAllocation proto.InternalMessageInfo

func (m *SignedAddressAllocation) GetAddressAllocation() *AddressAllocation {
	if m != nil {
		return m.AddressAllocation
	}
	return nil
}

func (m *SignedAddressAllocation) GetSignedAddressAllocation() []byte {
	if m != nil {
		return m.SignedAddressAllocation
	}
	return nil
}

type AllocateAddressRequest struct {
	AddressAllocation    *AddressAllocation `protobuf:"bytes,1,opt,name=addressAllocation,proto3" json:"addressAllocation,omitempty"`
	Family               Family             `protobuf:"varint,2,opt,name=family,proto3,enum=com.netflix.titus.Family" json:"family,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AllocateAddressRequest) Reset()         { *m = AllocateAddressRequest{} }
func (m *AllocateAddressRequest) String() string { return proto.CompactTextString(m) }
func (*AllocateAddressRequest) ProtoMessage()    {}
func (*AllocateAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_vpc_api_287c2149623615e8, []int{4}
}
func (m *AllocateAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocateAddressRequest.Unmarshal(m, b)
}
func (m *AllocateAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocateAddressRequest.Marshal(b, m, deterministic)
}
func (dst *AllocateAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocateAddressRequest.Merge(dst, src)
}
func (m *AllocateAddressRequest) XXX_Size() int {
	return xxx_messageInfo_AllocateAddressRequest.Size(m)
}
func (m *AllocateAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocateAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllocateAddressRequest proto.InternalMessageInfo

func (m *AllocateAddressRequest) GetAddressAllocation() *AddressAllocation {
	if m != nil {
		return m.AddressAllocation
	}
	return nil
}

func (m *AllocateAddressRequest) GetFamily() Family {
	if m != nil {
		return m.Family
	}
	return Family_FAMILY_DEFAULT
}

type AllocateAddressResponse struct {
	SignedAddressAllocation *SignedAddressAllocation `protobuf:"bytes,1,opt,name=signedAddressAllocation,proto3" json:"signedAddressAllocation,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *AllocateAddressResponse) Reset()         { *m = AllocateAddressResponse{} }
func (m *AllocateAddressResponse) String() string { return proto.CompactTextString(m) }
func (*AllocateAddressResponse) ProtoMessage()    {}
func (*AllocateAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_vpc_api_287c2149623615e8, []int{5}
}
func (m *AllocateAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocateAddressResponse.Unmarshal(m, b)
}
func (m *AllocateAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocateAddressResponse.Marshal(b, m, deterministic)
}
func (dst *AllocateAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocateAddressResponse.Merge(dst, src)
}
func (m *AllocateAddressResponse) XXX_Size() int {
	return xxx_messageInfo_AllocateAddressResponse.Size(m)
}
func (m *AllocateAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocateAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllocateAddressResponse proto.InternalMessageInfo

func (m *AllocateAddressResponse) GetSignedAddressAllocation() *SignedAddressAllocation {
	if m != nil {
		return m.SignedAddressAllocation
	}
	return nil
}

type GetAllocationRequest struct {
	// Types that are valid to be assigned to SearchParameter:
	//	*GetAllocationRequest_Address
	//	*GetAllocationRequest_Uuid
	SearchParameter      isGetAllocationRequest_SearchParameter `protobuf_oneof:"searchParameter"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *GetAllocationRequest) Reset()         { *m = GetAllocationRequest{} }
func (m *GetAllocationRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllocationRequest) ProtoMessage()    {}
func (*GetAllocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_vpc_api_287c2149623615e8, []int{6}
}
func (m *GetAllocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllocationRequest.Unmarshal(m, b)
}
func (m *GetAllocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllocationRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllocationRequest.Merge(dst, src)
}
func (m *GetAllocationRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllocationRequest.Size(m)
}
func (m *GetAllocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllocationRequest proto.InternalMessageInfo

type isGetAllocationRequest_SearchParameter interface {
	isGetAllocationRequest_SearchParameter()
}

type GetAllocationRequest_Address struct {
	Address *Address `protobuf:"bytes,1,opt,name=address,proto3,oneof"`
}

type GetAllocationRequest_Uuid struct {
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3,oneof"`
}

func (*GetAllocationRequest_Address) isGetAllocationRequest_SearchParameter() {}

func (*GetAllocationRequest_Uuid) isGetAllocationRequest_SearchParameter() {}

func (m *GetAllocationRequest) GetSearchParameter() isGetAllocationRequest_SearchParameter {
	if m != nil {
		return m.SearchParameter
	}
	return nil
}

func (m *GetAllocationRequest) GetAddress() *Address {
	if x, ok := m.GetSearchParameter().(*GetAllocationRequest_Address); ok {
		return x.Address
	}
	return nil
}

func (m *GetAllocationRequest) GetUuid() string {
	if x, ok := m.GetSearchParameter().(*GetAllocationRequest_Uuid); ok {
		return x.Uuid
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetAllocationRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetAllocationRequest_OneofMarshaler, _GetAllocationRequest_OneofUnmarshaler, _GetAllocationRequest_OneofSizer, []interface{}{
		(*GetAllocationRequest_Address)(nil),
		(*GetAllocationRequest_Uuid)(nil),
	}
}

func _GetAllocationRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetAllocationRequest)
	// searchParameter
	switch x := m.SearchParameter.(type) {
	case *GetAllocationRequest_Address:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Address); err != nil {
			return err
		}
	case *GetAllocationRequest_Uuid:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Uuid)
	case nil:
	default:
		return fmt.Errorf("GetAllocationRequest.SearchParameter has unexpected type %T", x)
	}
	return nil
}

func _GetAllocationRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetAllocationRequest)
	switch tag {
	case 1: // searchParameter.address
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Address)
		err := b.DecodeMessage(msg)
		m.SearchParameter = &GetAllocationRequest_Address{msg}
		return true, err
	case 2: // searchParameter.uuid
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.SearchParameter = &GetAllocationRequest_Uuid{x}
		return true, err
	default:
		return false, nil
	}
}

func _GetAllocationRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetAllocationRequest)
	// searchParameter
	switch x := m.SearchParameter.(type) {
	case *GetAllocationRequest_Address:
		s := proto.Size(x.Address)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetAllocationRequest_Uuid:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Uuid)))
		n += len(x.Uuid)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Address)(nil), "com.netflix.titus.Address")
	proto.RegisterType((*AddressLocation)(nil), "com.netflix.titus.AddressLocation")
	proto.RegisterType((*AddressAllocation)(nil), "com.netflix.titus.AddressAllocation")
	proto.RegisterType((*SignedAddressAllocation)(nil), "com.netflix.titus.SignedAddressAllocation")
	proto.RegisterType((*AllocateAddressRequest)(nil), "com.netflix.titus.AllocateAddressRequest")
	proto.RegisterType((*AllocateAddressResponse)(nil), "com.netflix.titus.AllocateAddressResponse")
	proto.RegisterType((*GetAllocationRequest)(nil), "com.netflix.titus.GetAllocationRequest")
	proto.RegisterEnum("com.netflix.titus.Family", Family_name, Family_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserIPServiceClient is the client API for UserIPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserIPServiceClient interface {
	// Static IP Address flow
	AllocateAddress(ctx context.Context, in *AllocateAddressRequest, opts ...grpc.CallOption) (*AllocateAddressResponse, error)
	GetAllocation(ctx context.Context, in *GetAllocationRequest, opts ...grpc.CallOption) (*AllocateAddressResponse, error)
}

type userIPServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserIPServiceClient(cc *grpc.ClientConn) UserIPServiceClient {
	return &userIPServiceClient{cc}
}

func (c *userIPServiceClient) AllocateAddress(ctx context.Context, in *AllocateAddressRequest, opts ...grpc.CallOption) (*AllocateAddressResponse, error) {
	out := new(AllocateAddressResponse)
	err := c.cc.Invoke(ctx, "/com.netflix.titus.UserIPService/AllocateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userIPServiceClient) GetAllocation(ctx context.Context, in *GetAllocationRequest, opts ...grpc.CallOption) (*AllocateAddressResponse, error) {
	out := new(AllocateAddressResponse)
	err := c.cc.Invoke(ctx, "/com.netflix.titus.UserIPService/GetAllocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserIPServiceServer is the server API for UserIPService service.
type UserIPServiceServer interface {
	// Static IP Address flow
	AllocateAddress(context.Context, *AllocateAddressRequest) (*AllocateAddressResponse, error)
	GetAllocation(context.Context, *GetAllocationRequest) (*AllocateAddressResponse, error)
}

func RegisterUserIPServiceServer(s *grpc.Server, srv UserIPServiceServer) {
	s.RegisterService(&_UserIPService_serviceDesc, srv)
}

func _UserIPService_AllocateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIPServiceServer).AllocateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.netflix.titus.UserIPService/AllocateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIPServiceServer).AllocateAddress(ctx, req.(*AllocateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserIPService_GetAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIPServiceServer).GetAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.netflix.titus.UserIPService/GetAllocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIPServiceServer).GetAllocation(ctx, req.(*GetAllocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserIPService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.netflix.titus.UserIPService",
	HandlerType: (*UserIPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateAddress",
			Handler:    _UserIPService_AllocateAddress_Handler,
		},
		{
			MethodName: "GetAllocation",
			Handler:    _UserIPService_GetAllocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netflix/titus/titus_vpc_api.proto",
}

func init() {
	proto.RegisterFile("netflix/titus/titus_vpc_api.proto", fileDescriptor_titus_vpc_api_287c2149623615e8)
}

var fileDescriptor_titus_vpc_api_287c2149623615e8 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0x16, 0x12, 0x3a, 0x90, 0x26, 0x59, 0x55, 0x4d, 0xc8, 0x05, 0x30, 0x48, 0x40,
	0x0e, 0x8e, 0x08, 0x55, 0x85, 0xb8, 0xa5, 0x82, 0xd0, 0x48, 0x41, 0xaa, 0x5c, 0x8a, 0x44, 0x2f,
	0xd1, 0xc6, 0x9e, 0xa4, 0x2b, 0xd9, 0x5e, 0x77, 0x77, 0x1d, 0xe8, 0x89, 0x47, 0xe1, 0xc8, 0x81,
	0x87, 0xe2, 0x55, 0x90, 0xd6, 0x9b, 0xbf, 0xb6, 0x11, 0x1c, 0x7a, 0x89, 0x76, 0x36, 0xbf, 0x99,
	0xf9, 0xe6, 0xdb, 0x49, 0xe0, 0x49, 0x84, 0x6a, 0x1a, 0xb0, 0x6f, 0x5d, 0xc5, 0x54, 0x22, 0xd3,
	0xcf, 0xf1, 0x3c, 0xf6, 0xc6, 0x34, 0x66, 0x4e, 0x2c, 0xb8, 0xe2, 0xa4, 0xe1, 0xf1, 0xd0, 0x31,
	0x98, 0xa3, 0x81, 0xf6, 0xa3, 0x19, 0xe7, 0xb3, 0x00, 0xbb, 0x1a, 0x98, 0x24, 0xd3, 0xae, 0x62,
	0x21, 0x4a, 0x45, 0xc3, 0x38, 0xcd, 0xb1, 0x9f, 0x42, 0xa5, 0xef, 0xfb, 0x02, 0xa5, 0x24, 0x2d,
	0xa8, 0xd0, 0xf4, 0xd8, 0xb2, 0x1e, 0x5b, 0x2f, 0xf6, 0xdc, 0x45, 0x68, 0x5f, 0x43, 0xcd, 0x40,
	0x23, 0xee, 0x51, 0xc5, 0x78, 0x44, 0x0e, 0xa1, 0x2c, 0x70, 0xc6, 0x78, 0x64, 0x58, 0x13, 0x91,
	0x0e, 0xd4, 0xe9, 0x9c, 0xb2, 0x80, 0x4e, 0x58, 0xc0, 0xd4, 0xcd, 0x25, 0x8f, 0xb0, 0xb5, 0xa3,
	0x89, 0xcc, 0x3d, 0x69, 0xc3, 0x3d, 0x99, 0x4c, 0x22, 0x54, 0x43, 0xbf, 0xb5, 0xab, 0x99, 0x65,
	0x6c, 0xff, 0xb2, 0xa0, 0x61, 0x7a, 0xf6, 0x83, 0x60, 0xd1, 0x75, 0x04, 0x35, 0xba, 0x29, 0x44,
	0xb7, 0xbf, 0xdf, 0xb3, 0x9d, 0xcc, 0xec, 0xce, 0x96, 0x64, 0x77, 0x3b, 0x95, 0x10, 0xb8, 0x93,
	0x24, 0xcc, 0x37, 0xfa, 0xf4, 0x99, 0x1c, 0xad, 0x4c, 0xd8, 0xd5, 0x95, 0xdb, 0xc5, 0x95, 0x57,
	0x06, 0xfd, 0xb4, 0xa0, 0x79, 0xce, 0x66, 0x11, 0xfa, 0x59, 0xcd, 0x2e, 0x34, 0xe8, 0xf6, 0xa5,
	0x51, 0xfd, 0xac, 0xb8, 0xf6, 0x8a, 0x75, 0xb3, 0xe9, 0xe4, 0x0d, 0x34, 0x65, 0x7e, 0x3b, 0x3d,
	0xcc, 0x03, 0xb7, 0xe8, 0x6b, 0xfb, 0x87, 0x05, 0x87, 0x26, 0xc4, 0xc5, 0x18, 0x78, 0x9d, 0xa0,
	0x54, 0xb7, 0x22, 0xf4, 0x15, 0x94, 0xa7, 0x34, 0x64, 0xc1, 0x8d, 0xd6, 0xb5, 0xdf, 0x7b, 0x98,
	0x53, 0x68, 0xa0, 0x01, 0xd7, 0x80, 0xf6, 0x77, 0x68, 0x66, 0x04, 0xca, 0x98, 0x47, 0x12, 0x89,
	0x5f, 0x3c, 0x76, 0xaa, 0xb3, 0x93, 0x53, 0xbe, 0xe0, 0x5d, 0x8a, 0x2d, 0xfa, 0x0a, 0x07, 0x1f,
	0x50, 0xad, 0x91, 0xc6, 0x9f, 0xe3, 0xcd, 0xdf, 0xc7, 0x5f, 0x57, 0xe3, 0xb4, 0xb4, 0x5c, 0x0e,
	0x72, 0xb0, 0xbe, 0x66, 0xa7, 0xa5, 0x74, 0xd1, 0x4e, 0x1a, 0x50, 0x93, 0x48, 0x85, 0x77, 0x75,
	0x46, 0x05, 0x0d, 0x51, 0xa1, 0xe8, 0xbc, 0x85, 0x72, 0xea, 0x05, 0x21, 0xb0, 0x3f, 0xe8, 0x7f,
	0x1c, 0x8e, 0xbe, 0x8c, 0xdf, 0xbd, 0x1f, 0xf4, 0x2f, 0x46, 0x9f, 0xea, 0x25, 0x52, 0x85, 0x3d,
	0x73, 0xf7, 0xf9, 0xa8, 0x6e, 0xad, 0x87, 0xc7, 0xf5, 0x9d, 0xde, 0x6f, 0x0b, 0xaa, 0x17, 0x12,
	0xc5, 0xf0, 0xec, 0x1c, 0xc5, 0x9c, 0x79, 0x48, 0xae, 0xa0, 0xb6, 0xe5, 0x23, 0x79, 0x99, 0x27,
	0x38, 0x77, 0x19, 0xda, 0x9d, 0x7f, 0x41, 0x97, 0xcf, 0x52, 0xdd, 0x30, 0x8c, 0x3c, 0xcf, 0x49,
	0xce, 0xb3, 0xf4, 0x7f, 0xba, 0x9c, 0x54, 0x2e, 0xef, 0x6a, 0x60, 0x52, 0xd6, 0xff, 0x5c, 0xaf,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x78, 0xd9, 0x16, 0x12, 0x05, 0x00, 0x00,
}
