// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netflix/titus/titus_base.proto

package titus

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

/// Titus scheduler tier (see Titus scheduler documentation for more information).
type Tier int32

const (
	/// Tier for running latency insensitive batch workloads.
	Tier_Flex Tier = 0
	/// Tier for running latency sensitive workloads.
	Tier_Critical Tier = 1
)

var Tier_name = map[int32]string{
	0: "Flex",
	1: "Critical",
}

var Tier_value = map[string]int32{
	"Flex":     0,
	"Critical": 1,
}

func (x Tier) String() string {
	return proto.EnumName(Tier_name, int32(x))
}

func (Tier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{0}
}

/// Titus hierarchy level.
type Level int32

const (
	Level_SystemLevel        Level = 0
	Level_TierLevel          Level = 1
	Level_CapacityGroupLevel Level = 2
	Level_JobLevel           Level = 3
	Level_TaskLevel          Level = 4
)

var Level_name = map[int32]string{
	0: "SystemLevel",
	1: "TierLevel",
	2: "CapacityGroupLevel",
	3: "JobLevel",
	4: "TaskLevel",
}

var Level_value = map[string]int32{
	"SystemLevel":        0,
	"TierLevel":          1,
	"CapacityGroupLevel": 2,
	"JobLevel":           3,
	"TaskLevel":          4,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{1}
}

/// Disk mount permission mask
type MountPerm int32

const (
	/// Read only
	MountPerm_RO MountPerm = 0
	// Write only
	MountPerm_WO MountPerm = 1
	// Read/write
	MountPerm_RW MountPerm = 2
)

var MountPerm_name = map[int32]string{
	0: "RO",
	1: "WO",
	2: "RW",
}

var MountPerm_value = map[string]int32{
	"RO": 0,
	"WO": 1,
	"RW": 2,
}

func (x MountPerm) String() string {
	return proto.EnumName(MountPerm_name, int32(x))
}

func (MountPerm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{2}
}

type Day int32

const (
	Day_Monday    Day = 0
	Day_Tuesday   Day = 1
	Day_Wednesday Day = 2
	Day_Thursday  Day = 3
	Day_Friday    Day = 4
	Day_Saturday  Day = 5
	Day_Sunday    Day = 6
)

var Day_name = map[int32]string{
	0: "Monday",
	1: "Tuesday",
	2: "Wednesday",
	3: "Thursday",
	4: "Friday",
	5: "Saturday",
	6: "Sunday",
}

var Day_value = map[string]int32{
	"Monday":    0,
	"Tuesday":   1,
	"Wednesday": 2,
	"Thursday":  3,
	"Friday":    4,
	"Saturday":  5,
	"Sunday":    6,
}

func (x Day) String() string {
	return proto.EnumName(Day_name, int32(x))
}

func (Day) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{3}
}

type CallMetadata_CallerType int32

const (
	CallMetadata_Unknown     CallMetadata_CallerType = 0
	CallMetadata_Application CallMetadata_CallerType = 1
	CallMetadata_User        CallMetadata_CallerType = 2
)

var CallMetadata_CallerType_name = map[int32]string{
	0: "Unknown",
	1: "Application",
	2: "User",
}

var CallMetadata_CallerType_value = map[string]int32{
	"Unknown":     0,
	"Application": 1,
	"User":        2,
}

func (x CallMetadata_CallerType) String() string {
	return proto.EnumName(CallMetadata_CallerType_name, int32(x))
}

func (CallMetadata_CallerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{0, 0}
}

/// Call metadata (caller's identity, call path).
type CallMetadata struct {
	/// (Required) The original caller identifier. Depending on the user identity (a user or an application), the format
	// of the id may be different. For example a user's id could be their email address, and application's id its name.
	//  (Deprecated) Use 'caller' field instead.
	CallerId string `protobuf:"bytes,1,opt,name=callerId,proto3" json:"callerId,omitempty"` // Deprecated: Do not use.
	/// The first item in the list is the original caller, followed by a sequence of intermediaries via which the
	//  original call was relayed.
	Callers []*CallMetadata_Caller `protobuf:"bytes,5,rep,name=callers,proto3" json:"callers,omitempty"`
	/// (Optional) The reason why a call was made.
	CallReason string `protobuf:"bytes,2,opt,name=callReason,proto3" json:"callReason,omitempty"`
	/// (Optional) The list of intermediaries via which a call was relayed.
	//  (Deprecated) Use 'caller' field instead.
	CallPath []string `protobuf:"bytes,3,rep,name=callPath,proto3" json:"callPath,omitempty"` // Deprecated: Do not use.
	/// (Optional) If set to true, a diagnostic information is provided if a request fails.
	Debug                bool     `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallMetadata) Reset()         { *m = CallMetadata{} }
func (m *CallMetadata) String() string { return proto.CompactTextString(m) }
func (*CallMetadata) ProtoMessage()    {}
func (*CallMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{0}
}

func (m *CallMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallMetadata.Unmarshal(m, b)
}
func (m *CallMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallMetadata.Marshal(b, m, deterministic)
}
func (m *CallMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallMetadata.Merge(m, src)
}
func (m *CallMetadata) XXX_Size() int {
	return xxx_messageInfo_CallMetadata.Size(m)
}
func (m *CallMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CallMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CallMetadata proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *CallMetadata) GetCallerId() string {
	if m != nil {
		return m.CallerId
	}
	return ""
}

func (m *CallMetadata) GetCallers() []*CallMetadata_Caller {
	if m != nil {
		return m.Callers
	}
	return nil
}

func (m *CallMetadata) GetCallReason() string {
	if m != nil {
		return m.CallReason
	}
	return ""
}

// Deprecated: Do not use.
func (m *CallMetadata) GetCallPath() []string {
	if m != nil {
		return m.CallPath
	}
	return nil
}

func (m *CallMetadata) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

type CallMetadata_Caller struct {
	/// (Required) A caller identifier. Depending on the user identity (a user or an application), the format
	// of the id may be different. For example a user's id could be their email address, and application's id its name.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	/// (Optional) The caller type.
	Type CallMetadata_CallerType `protobuf:"varint,2,opt,name=type,proto3,enum=com.netflix.titus.CallMetadata_CallerType" json:"type,omitempty"`
	/// (Optional) Additional data associated with the caller. Key names starting with 'titus' are reserved for Titus.
	//  Predefined context keys:
	//  * 'titus.service.name' - name of the service that is invoked
	//  * 'titus.service.method' - nome of the method that is invoked
	//  * 'titus.transport.type' - transport type (HTTP/GRPC)
	//  * 'titus.transport.secure' - true for TLS, false for plain text
	Context              map[string]string `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CallMetadata_Caller) Reset()         { *m = CallMetadata_Caller{} }
func (m *CallMetadata_Caller) String() string { return proto.CompactTextString(m) }
func (*CallMetadata_Caller) ProtoMessage()    {}
func (*CallMetadata_Caller) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{0, 0}
}

func (m *CallMetadata_Caller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallMetadata_Caller.Unmarshal(m, b)
}
func (m *CallMetadata_Caller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallMetadata_Caller.Marshal(b, m, deterministic)
}
func (m *CallMetadata_Caller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallMetadata_Caller.Merge(m, src)
}
func (m *CallMetadata_Caller) XXX_Size() int {
	return xxx_messageInfo_CallMetadata_Caller.Size(m)
}
func (m *CallMetadata_Caller) XXX_DiscardUnknown() {
	xxx_messageInfo_CallMetadata_Caller.DiscardUnknown(m)
}

var xxx_messageInfo_CallMetadata_Caller proto.InternalMessageInfo

func (m *CallMetadata_Caller) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CallMetadata_Caller) GetType() CallMetadata_CallerType {
	if m != nil {
		return m.Type
	}
	return CallMetadata_Unknown
}

func (m *CallMetadata_Caller) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

/// An entity representing single page of a collection. Prefer using cursor-based pagination, pageNumber is being retired.
//  For the first page, leave both pageNumber and cursor empty.
type Page struct {
	/// (Optional) Requested page number, starting from 0 (defaults to 0 if not specified).
	//  (Deprecated) Use cursor-based pagination instead.
	PageNumber int32 `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"` // Deprecated: Do not use.
	/// (Required) Requested page size (if not specified, default size is operation specific).
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	/// (Optional) The position in the collection from which the next page should be returned. If the cursor value is set, it is
	// always used, irrespective of the page number set.
	Cursor               string   `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{1}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *Page) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *Page) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Page) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

/// An entity representing pagination information returned to a client iterating over its elements.
// It includes current page that the client requested, and the total collection size.
// As not always pageCount * pageSize == itemCount, the item count is included as well.
type Pagination struct {
	/// (Required) Requested page details.
	CurrentPage *Page `protobuf:"bytes,1,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	/// Are there any more items to return? Use the cursor to fetch the next page when required.
	HasMore bool `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	/// (Deprecated) Use cursor-based pagination instead. Total number of pages.
	TotalPages int32 `protobuf:"varint,3,opt,name=totalPages,proto3" json:"totalPages,omitempty"` // Deprecated: Do not use.
	/// Total number of items.
	TotalItems int32 `protobuf:"varint,4,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	/// The last retrieved item's position in the collection. The cursor value can be sent on a subsequent request to
	// get the next page of items. Using cursors, instead of page numbers, will guarantee that all items are
	// retrieved with a potential of items being duplicated.
	Cursor string `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	/// Position of the cursor relative to totalItems. It can be used to determine what pageNumber would overlap with a
	// cursor, or to provide an idea of progress when walking all pages. Valid values are [0, totalItems-1].
	CursorPosition       int32    `protobuf:"varint,6,opt,name=cursorPosition,proto3" json:"cursorPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{2}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetCurrentPage() *Page {
	if m != nil {
		return m.CurrentPage
	}
	return nil
}

func (m *Pagination) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

// Deprecated: Do not use.
func (m *Pagination) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *Pagination) GetTotalItems() int32 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *Pagination) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *Pagination) GetCursorPosition() int32 {
	if m != nil {
		return m.CursorPosition
	}
	return 0
}

/// Retry polices.
type RetryPolicy struct {
	/// (Required) Retry policy.
	//
	// Types that are valid to be assigned to Policy:
	//	*RetryPolicy_Immediate_
	//	*RetryPolicy_Delayed_
	//	*RetryPolicy_ExponentialBackOff_
	Policy               isRetryPolicy_Policy `protobuf_oneof:"Policy"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RetryPolicy) Reset()         { *m = RetryPolicy{} }
func (m *RetryPolicy) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy) ProtoMessage()    {}
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{3}
}

func (m *RetryPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryPolicy.Unmarshal(m, b)
}
func (m *RetryPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryPolicy.Marshal(b, m, deterministic)
}
func (m *RetryPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy.Merge(m, src)
}
func (m *RetryPolicy) XXX_Size() int {
	return xxx_messageInfo_RetryPolicy.Size(m)
}
func (m *RetryPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy proto.InternalMessageInfo

type isRetryPolicy_Policy interface {
	isRetryPolicy_Policy()
}

type RetryPolicy_Immediate_ struct {
	Immediate *RetryPolicy_Immediate `protobuf:"bytes,1,opt,name=immediate,proto3,oneof"`
}

type RetryPolicy_Delayed_ struct {
	Delayed *RetryPolicy_Delayed `protobuf:"bytes,2,opt,name=delayed,proto3,oneof"`
}

type RetryPolicy_ExponentialBackOff_ struct {
	ExponentialBackOff *RetryPolicy_ExponentialBackOff `protobuf:"bytes,3,opt,name=exponentialBackOff,proto3,oneof"`
}

func (*RetryPolicy_Immediate_) isRetryPolicy_Policy() {}

func (*RetryPolicy_Delayed_) isRetryPolicy_Policy() {}

func (*RetryPolicy_ExponentialBackOff_) isRetryPolicy_Policy() {}

func (m *RetryPolicy) GetPolicy() isRetryPolicy_Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *RetryPolicy) GetImmediate() *RetryPolicy_Immediate {
	if x, ok := m.GetPolicy().(*RetryPolicy_Immediate_); ok {
		return x.Immediate
	}
	return nil
}

func (m *RetryPolicy) GetDelayed() *RetryPolicy_Delayed {
	if x, ok := m.GetPolicy().(*RetryPolicy_Delayed_); ok {
		return x.Delayed
	}
	return nil
}

func (m *RetryPolicy) GetExponentialBackOff() *RetryPolicy_ExponentialBackOff {
	if x, ok := m.GetPolicy().(*RetryPolicy_ExponentialBackOff_); ok {
		return x.ExponentialBackOff
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RetryPolicy) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RetryPolicy_Immediate_)(nil),
		(*RetryPolicy_Delayed_)(nil),
		(*RetryPolicy_ExponentialBackOff_)(nil),
	}
}

/// Re-run immediately.
type RetryPolicy_Immediate struct {
	/// Maximum number of retries.
	Retries              uint32   `protobuf:"varint,1,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryPolicy_Immediate) Reset()         { *m = RetryPolicy_Immediate{} }
func (m *RetryPolicy_Immediate) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy_Immediate) ProtoMessage()    {}
func (*RetryPolicy_Immediate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{3, 0}
}

func (m *RetryPolicy_Immediate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryPolicy_Immediate.Unmarshal(m, b)
}
func (m *RetryPolicy_Immediate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryPolicy_Immediate.Marshal(b, m, deterministic)
}
func (m *RetryPolicy_Immediate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy_Immediate.Merge(m, src)
}
func (m *RetryPolicy_Immediate) XXX_Size() int {
	return xxx_messageInfo_RetryPolicy_Immediate.Size(m)
}
func (m *RetryPolicy_Immediate) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy_Immediate.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy_Immediate proto.InternalMessageInfo

func (m *RetryPolicy_Immediate) GetRetries() uint32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

/// Re-run after a given delay.
type RetryPolicy_Delayed struct {
	/// Initial delay in milliseconds.
	InitialDelayMs uint64 `protobuf:"varint,1,opt,name=initialDelayMs,proto3" json:"initialDelayMs,omitempty"`
	/// Subsequent delays in milliseconds.
	DelayMs uint64 `protobuf:"varint,2,opt,name=delayMs,proto3" json:"delayMs,omitempty"`
	/// Maximum number of retries.
	Retries              uint32   `protobuf:"varint,3,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryPolicy_Delayed) Reset()         { *m = RetryPolicy_Delayed{} }
func (m *RetryPolicy_Delayed) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy_Delayed) ProtoMessage()    {}
func (*RetryPolicy_Delayed) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{3, 1}
}

func (m *RetryPolicy_Delayed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryPolicy_Delayed.Unmarshal(m, b)
}
func (m *RetryPolicy_Delayed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryPolicy_Delayed.Marshal(b, m, deterministic)
}
func (m *RetryPolicy_Delayed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy_Delayed.Merge(m, src)
}
func (m *RetryPolicy_Delayed) XXX_Size() int {
	return xxx_messageInfo_RetryPolicy_Delayed.Size(m)
}
func (m *RetryPolicy_Delayed) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy_Delayed.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy_Delayed proto.InternalMessageInfo

func (m *RetryPolicy_Delayed) GetInitialDelayMs() uint64 {
	if m != nil {
		return m.InitialDelayMs
	}
	return 0
}

func (m *RetryPolicy_Delayed) GetDelayMs() uint64 {
	if m != nil {
		return m.DelayMs
	}
	return 0
}

func (m *RetryPolicy_Delayed) GetRetries() uint32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

/// Exponential back-off retry policy.
type RetryPolicy_ExponentialBackOff struct {
	/// Initial delay in milliseconds.
	InitialDelayMs uint64 `protobuf:"varint,1,opt,name=initialDelayMs,proto3" json:"initialDelayMs,omitempty"`
	/// Upper bound on delay interval.
	MaxDelayIntervalMs uint64 `protobuf:"varint,2,opt,name=maxDelayIntervalMs,proto3" json:"maxDelayIntervalMs,omitempty"`
	/// Maximum number of retries.
	Retries              uint32   `protobuf:"varint,3,opt,name=retries,proto3" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryPolicy_ExponentialBackOff) Reset()         { *m = RetryPolicy_ExponentialBackOff{} }
func (m *RetryPolicy_ExponentialBackOff) String() string { return proto.CompactTextString(m) }
func (*RetryPolicy_ExponentialBackOff) ProtoMessage()    {}
func (*RetryPolicy_ExponentialBackOff) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{3, 2}
}

func (m *RetryPolicy_ExponentialBackOff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryPolicy_ExponentialBackOff.Unmarshal(m, b)
}
func (m *RetryPolicy_ExponentialBackOff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryPolicy_ExponentialBackOff.Marshal(b, m, deterministic)
}
func (m *RetryPolicy_ExponentialBackOff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryPolicy_ExponentialBackOff.Merge(m, src)
}
func (m *RetryPolicy_ExponentialBackOff) XXX_Size() int {
	return xxx_messageInfo_RetryPolicy_ExponentialBackOff.Size(m)
}
func (m *RetryPolicy_ExponentialBackOff) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryPolicy_ExponentialBackOff.DiscardUnknown(m)
}

var xxx_messageInfo_RetryPolicy_ExponentialBackOff proto.InternalMessageInfo

func (m *RetryPolicy_ExponentialBackOff) GetInitialDelayMs() uint64 {
	if m != nil {
		return m.InitialDelayMs
	}
	return 0
}

func (m *RetryPolicy_ExponentialBackOff) GetMaxDelayIntervalMs() uint64 {
	if m != nil {
		return m.MaxDelayIntervalMs
	}
	return 0
}

func (m *RetryPolicy_ExponentialBackOff) GetRetries() uint32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

/// Token bucket policies
type TokenBucketPolicy struct {
	Capacity              uint64 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	InitialNumberOfTokens uint64 `protobuf:"varint,2,opt,name=initialNumberOfTokens,proto3" json:"initialNumberOfTokens,omitempty"`
	// Types that are valid to be assigned to RefillStrategy:
	//	*TokenBucketPolicy_FixedIntervalRefillStrategy_
	RefillStrategy       isTokenBucketPolicy_RefillStrategy `protobuf_oneof:"RefillStrategy"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *TokenBucketPolicy) Reset()         { *m = TokenBucketPolicy{} }
func (m *TokenBucketPolicy) String() string { return proto.CompactTextString(m) }
func (*TokenBucketPolicy) ProtoMessage()    {}
func (*TokenBucketPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{4}
}

func (m *TokenBucketPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenBucketPolicy.Unmarshal(m, b)
}
func (m *TokenBucketPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenBucketPolicy.Marshal(b, m, deterministic)
}
func (m *TokenBucketPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenBucketPolicy.Merge(m, src)
}
func (m *TokenBucketPolicy) XXX_Size() int {
	return xxx_messageInfo_TokenBucketPolicy.Size(m)
}
func (m *TokenBucketPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenBucketPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_TokenBucketPolicy proto.InternalMessageInfo

func (m *TokenBucketPolicy) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *TokenBucketPolicy) GetInitialNumberOfTokens() uint64 {
	if m != nil {
		return m.InitialNumberOfTokens
	}
	return 0
}

type isTokenBucketPolicy_RefillStrategy interface {
	isTokenBucketPolicy_RefillStrategy()
}

type TokenBucketPolicy_FixedIntervalRefillStrategy_ struct {
	FixedIntervalRefillStrategy *TokenBucketPolicy_FixedIntervalRefillStrategy `protobuf:"bytes,3,opt,name=fixedIntervalRefillStrategy,proto3,oneof"`
}

func (*TokenBucketPolicy_FixedIntervalRefillStrategy_) isTokenBucketPolicy_RefillStrategy() {}

func (m *TokenBucketPolicy) GetRefillStrategy() isTokenBucketPolicy_RefillStrategy {
	if m != nil {
		return m.RefillStrategy
	}
	return nil
}

func (m *TokenBucketPolicy) GetFixedIntervalRefillStrategy() *TokenBucketPolicy_FixedIntervalRefillStrategy {
	if x, ok := m.GetRefillStrategy().(*TokenBucketPolicy_FixedIntervalRefillStrategy_); ok {
		return x.FixedIntervalRefillStrategy
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TokenBucketPolicy) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TokenBucketPolicy_FixedIntervalRefillStrategy_)(nil),
	}
}

type TokenBucketPolicy_FixedIntervalRefillStrategy struct {
	RefillRate           uint64   `protobuf:"varint,3,opt,name=refillRate,proto3" json:"refillRate,omitempty"`
	IntervalMs           uint64   `protobuf:"varint,4,opt,name=intervalMs,proto3" json:"intervalMs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) Reset() {
	*m = TokenBucketPolicy_FixedIntervalRefillStrategy{}
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) String() string {
	return proto.CompactTextString(m)
}
func (*TokenBucketPolicy_FixedIntervalRefillStrategy) ProtoMessage() {}
func (*TokenBucketPolicy_FixedIntervalRefillStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{4, 0}
}

func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.Unmarshal(m, b)
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.Marshal(b, m, deterministic)
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.Merge(m, src)
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_Size() int {
	return xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.Size(m)
}
func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_TokenBucketPolicy_FixedIntervalRefillStrategy proto.InternalMessageInfo

func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) GetRefillRate() uint64 {
	if m != nil {
		return m.RefillRate
	}
	return 0
}

func (m *TokenBucketPolicy_FixedIntervalRefillStrategy) GetIntervalMs() uint64 {
	if m != nil {
		return m.IntervalMs
	}
	return 0
}

/// A reference to an entity in the Titus hierarchy.
type Reference struct {
	// Types that are valid to be assigned to Reference:
	//	*Reference_System_
	//	*Reference_Tier
	//	*Reference_CapacityGroup
	//	*Reference_JobId
	//	*Reference_TaskId
	Reference            isReference_Reference `protobuf_oneof:"Reference"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Reference) Reset()         { *m = Reference{} }
func (m *Reference) String() string { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()    {}
func (*Reference) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{5}
}

func (m *Reference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference.Unmarshal(m, b)
}
func (m *Reference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference.Marshal(b, m, deterministic)
}
func (m *Reference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference.Merge(m, src)
}
func (m *Reference) XXX_Size() int {
	return xxx_messageInfo_Reference.Size(m)
}
func (m *Reference) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference.DiscardUnknown(m)
}

var xxx_messageInfo_Reference proto.InternalMessageInfo

type isReference_Reference interface {
	isReference_Reference()
}

type Reference_System_ struct {
	System *Reference_System `protobuf:"bytes,1,opt,name=system,proto3,oneof"`
}

type Reference_Tier struct {
	Tier Tier `protobuf:"varint,2,opt,name=tier,proto3,enum=com.netflix.titus.Tier,oneof"`
}

type Reference_CapacityGroup struct {
	CapacityGroup string `protobuf:"bytes,3,opt,name=capacityGroup,proto3,oneof"`
}

type Reference_JobId struct {
	JobId string `protobuf:"bytes,4,opt,name=jobId,proto3,oneof"`
}

type Reference_TaskId struct {
	TaskId string `protobuf:"bytes,5,opt,name=taskId,proto3,oneof"`
}

func (*Reference_System_) isReference_Reference() {}

func (*Reference_Tier) isReference_Reference() {}

func (*Reference_CapacityGroup) isReference_Reference() {}

func (*Reference_JobId) isReference_Reference() {}

func (*Reference_TaskId) isReference_Reference() {}

func (m *Reference) GetReference() isReference_Reference {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *Reference) GetSystem() *Reference_System {
	if x, ok := m.GetReference().(*Reference_System_); ok {
		return x.System
	}
	return nil
}

func (m *Reference) GetTier() Tier {
	if x, ok := m.GetReference().(*Reference_Tier); ok {
		return x.Tier
	}
	return Tier_Flex
}

func (m *Reference) GetCapacityGroup() string {
	if x, ok := m.GetReference().(*Reference_CapacityGroup); ok {
		return x.CapacityGroup
	}
	return ""
}

func (m *Reference) GetJobId() string {
	if x, ok := m.GetReference().(*Reference_JobId); ok {
		return x.JobId
	}
	return ""
}

func (m *Reference) GetTaskId() string {
	if x, ok := m.GetReference().(*Reference_TaskId); ok {
		return x.TaskId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Reference) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Reference_System_)(nil),
		(*Reference_Tier)(nil),
		(*Reference_CapacityGroup)(nil),
		(*Reference_JobId)(nil),
		(*Reference_TaskId)(nil),
	}
}

type Reference_System struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reference_System) Reset()         { *m = Reference_System{} }
func (m *Reference_System) String() string { return proto.CompactTextString(m) }
func (*Reference_System) ProtoMessage()    {}
func (*Reference_System) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{5, 0}
}

func (m *Reference_System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference_System.Unmarshal(m, b)
}
func (m *Reference_System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference_System.Marshal(b, m, deterministic)
}
func (m *Reference_System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference_System.Merge(m, src)
}
func (m *Reference_System) XXX_Size() int {
	return xxx_messageInfo_Reference_System.Size(m)
}
func (m *Reference_System) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference_System.DiscardUnknown(m)
}

var xxx_messageInfo_Reference_System proto.InternalMessageInfo

/// Instance resource dimensions
type ResourceDimension struct {
	Cpu                  uint32   `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu                  uint32   `protobuf:"varint,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	MemoryMB             uint32   `protobuf:"varint,3,opt,name=memoryMB,proto3" json:"memoryMB,omitempty"`
	DiskMB               uint32   `protobuf:"varint,4,opt,name=diskMB,proto3" json:"diskMB,omitempty"`
	NetworkMbps          uint32   `protobuf:"varint,5,opt,name=networkMbps,proto3" json:"networkMbps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceDimension) Reset()         { *m = ResourceDimension{} }
func (m *ResourceDimension) String() string { return proto.CompactTextString(m) }
func (*ResourceDimension) ProtoMessage()    {}
func (*ResourceDimension) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{6}
}

func (m *ResourceDimension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceDimension.Unmarshal(m, b)
}
func (m *ResourceDimension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceDimension.Marshal(b, m, deterministic)
}
func (m *ResourceDimension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceDimension.Merge(m, src)
}
func (m *ResourceDimension) XXX_Size() int {
	return xxx_messageInfo_ResourceDimension.Size(m)
}
func (m *ResourceDimension) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceDimension.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceDimension proto.InternalMessageInfo

func (m *ResourceDimension) GetCpu() uint32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *ResourceDimension) GetGpu() uint32 {
	if m != nil {
		return m.Gpu
	}
	return 0
}

func (m *ResourceDimension) GetMemoryMB() uint32 {
	if m != nil {
		return m.MemoryMB
	}
	return 0
}

func (m *ResourceDimension) GetDiskMB() uint32 {
	if m != nil {
		return m.DiskMB
	}
	return 0
}

func (m *ResourceDimension) GetNetworkMbps() uint32 {
	if m != nil {
		return m.NetworkMbps
	}
	return 0
}

/// Time window descriptor.
type TimeWindow struct {
	/// (Required) Included days.
	Days []Day `protobuf:"varint,1,rep,packed,name=days,proto3,enum=com.netflix.titus.Day" json:"days,omitempty"`
	/// (Optional) Included hour ranges. If not set, defaults to 0-24.
	HourlyTimeWindows []*TimeWindow_HourlyTimeWindow `protobuf:"bytes,2,rep,name=hourlyTimeWindows,proto3" json:"hourlyTimeWindows,omitempty"`
	/// (Optional) If not set, UTC time zone is set as a default.
	TimeZone             string   `protobuf:"bytes,3,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeWindow) Reset()         { *m = TimeWindow{} }
func (m *TimeWindow) String() string { return proto.CompactTextString(m) }
func (*TimeWindow) ProtoMessage()    {}
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{7}
}

func (m *TimeWindow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeWindow.Unmarshal(m, b)
}
func (m *TimeWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeWindow.Marshal(b, m, deterministic)
}
func (m *TimeWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeWindow.Merge(m, src)
}
func (m *TimeWindow) XXX_Size() int {
	return xxx_messageInfo_TimeWindow.Size(m)
}
func (m *TimeWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeWindow.DiscardUnknown(m)
}

var xxx_messageInfo_TimeWindow proto.InternalMessageInfo

func (m *TimeWindow) GetDays() []Day {
	if m != nil {
		return m.Days
	}
	return nil
}

func (m *TimeWindow) GetHourlyTimeWindows() []*TimeWindow_HourlyTimeWindow {
	if m != nil {
		return m.HourlyTimeWindows
	}
	return nil
}

func (m *TimeWindow) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

type TimeWindow_HourlyTimeWindow struct {
	/// (Required) Starting hour.
	StartHour uint32 `protobuf:"varint,1,opt,name=startHour,proto3" json:"startHour,omitempty"`
	/// (Required) Ending hour.
	EndHour              uint32   `protobuf:"varint,2,opt,name=endHour,proto3" json:"endHour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeWindow_HourlyTimeWindow) Reset()         { *m = TimeWindow_HourlyTimeWindow{} }
func (m *TimeWindow_HourlyTimeWindow) String() string { return proto.CompactTextString(m) }
func (*TimeWindow_HourlyTimeWindow) ProtoMessage()    {}
func (*TimeWindow_HourlyTimeWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{7, 0}
}

func (m *TimeWindow_HourlyTimeWindow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeWindow_HourlyTimeWindow.Unmarshal(m, b)
}
func (m *TimeWindow_HourlyTimeWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeWindow_HourlyTimeWindow.Marshal(b, m, deterministic)
}
func (m *TimeWindow_HourlyTimeWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeWindow_HourlyTimeWindow.Merge(m, src)
}
func (m *TimeWindow_HourlyTimeWindow) XXX_Size() int {
	return xxx_messageInfo_TimeWindow_HourlyTimeWindow.Size(m)
}
func (m *TimeWindow_HourlyTimeWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeWindow_HourlyTimeWindow.DiscardUnknown(m)
}

var xxx_messageInfo_TimeWindow_HourlyTimeWindow proto.InternalMessageInfo

func (m *TimeWindow_HourlyTimeWindow) GetStartHour() uint32 {
	if m != nil {
		return m.StartHour
	}
	return 0
}

func (m *TimeWindow_HourlyTimeWindow) GetEndHour() uint32 {
	if m != nil {
		return m.EndHour
	}
	return 0
}

/// A provider for container health
type ContainerHealthProvider struct {
	/// (Required) The name of the provider.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	/// (Optional) Attributes to be used by the provider.
	Attributes           map[string]string `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ContainerHealthProvider) Reset()         { *m = ContainerHealthProvider{} }
func (m *ContainerHealthProvider) String() string { return proto.CompactTextString(m) }
func (*ContainerHealthProvider) ProtoMessage()    {}
func (*ContainerHealthProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{8}
}

func (m *ContainerHealthProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerHealthProvider.Unmarshal(m, b)
}
func (m *ContainerHealthProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerHealthProvider.Marshal(b, m, deterministic)
}
func (m *ContainerHealthProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerHealthProvider.Merge(m, src)
}
func (m *ContainerHealthProvider) XXX_Size() int {
	return xxx_messageInfo_ContainerHealthProvider.Size(m)
}
func (m *ContainerHealthProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerHealthProvider.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerHealthProvider proto.InternalMessageInfo

func (m *ContainerHealthProvider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainerHealthProvider) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

/// The location within the VPC where the address exists.
type AddressLocation struct {
	/// (Required) Region the address exists in.
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	/// (Required) Availability zone the address exists in.
	AvailabilityZone string `protobuf:"bytes,2,opt,name=availabilityZone,proto3" json:"availabilityZone,omitempty"`
	/// (Required) Subnet the address exists in.
	SubnetId             string   `protobuf:"bytes,3,opt,name=subnetId,proto3" json:"subnetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressLocation) Reset()         { *m = AddressLocation{} }
func (m *AddressLocation) String() string { return proto.CompactTextString(m) }
func (*AddressLocation) ProtoMessage()    {}
func (*AddressLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{9}
}

func (m *AddressLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressLocation.Unmarshal(m, b)
}
func (m *AddressLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressLocation.Marshal(b, m, deterministic)
}
func (m *AddressLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressLocation.Merge(m, src)
}
func (m *AddressLocation) XXX_Size() int {
	return xxx_messageInfo_AddressLocation.Size(m)
}
func (m *AddressLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressLocation.DiscardUnknown(m)
}

var xxx_messageInfo_AddressLocation proto.InternalMessageInfo

func (m *AddressLocation) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *AddressLocation) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

func (m *AddressLocation) GetSubnetId() string {
	if m != nil {
		return m.SubnetId
	}
	return ""
}

/// An IP address allocation from the Titus VPC service.
type AddressAllocation struct {
	/// (Required) The location of the address within the VPC.
	AddressLocation *AddressLocation `protobuf:"bytes,1,opt,name=addressLocation,proto3" json:"addressLocation,omitempty"`
	/// (Required) A valid UUID4. It should be set during VPC service allocation, if unset, one will be set for you.
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	/// (Required) The VPC IP address. The address must be unset when requesting an allocation from the VPC service.
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressAllocation) Reset()         { *m = AddressAllocation{} }
func (m *AddressAllocation) String() string { return proto.CompactTextString(m) }
func (*AddressAllocation) ProtoMessage()    {}
func (*AddressAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{10}
}

func (m *AddressAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressAllocation.Unmarshal(m, b)
}
func (m *AddressAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressAllocation.Marshal(b, m, deterministic)
}
func (m *AddressAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressAllocation.Merge(m, src)
}
func (m *AddressAllocation) XXX_Size() int {
	return xxx_messageInfo_AddressAllocation.Size(m)
}
func (m *AddressAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_AddressAllocation proto.InternalMessageInfo

func (m *AddressAllocation) GetAddressLocation() *AddressLocation {
	if m != nil {
		return m.AddressLocation
	}
	return nil
}

func (m *AddressAllocation) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddressAllocation) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type StaticIPAddressIDs struct {
	/// (Required) A list of valid UUIDs
	Uuids                []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticIPAddressIDs) Reset()         { *m = StaticIPAddressIDs{} }
func (m *StaticIPAddressIDs) String() string { return proto.CompactTextString(m) }
func (*StaticIPAddressIDs) ProtoMessage()    {}
func (*StaticIPAddressIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{11}
}

func (m *StaticIPAddressIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticIPAddressIDs.Unmarshal(m, b)
}
func (m *StaticIPAddressIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticIPAddressIDs.Marshal(b, m, deterministic)
}
func (m *StaticIPAddressIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticIPAddressIDs.Merge(m, src)
}
func (m *StaticIPAddressIDs) XXX_Size() int {
	return xxx_messageInfo_StaticIPAddressIDs.Size(m)
}
func (m *StaticIPAddressIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticIPAddressIDs.DiscardUnknown(m)
}

var xxx_messageInfo_StaticIPAddressIDs proto.InternalMessageInfo

func (m *StaticIPAddressIDs) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

/// An IP address allocation signed by the Titus VPC service.
type SignedAddressAllocation struct {
	/// (Required) The IP address and metadata that was allocated.
	AddressAllocation *AddressAllocation `protobuf:"bytes,1,opt,name=addressAllocation,proto3" json:"addressAllocation,omitempty"`
	// This is an x509v3 signed version of the address allocation.
	SignedAddressAllocation []byte `protobuf:"bytes,2,opt,name=signedAddressAllocation,proto3" json:"signedAddressAllocation,omitempty"` // Deprecated: Do not use.
	// authoritative publicKey is the key that came from the database
	AuthoritativePublicKey []byte `protobuf:"bytes,3,opt,name=authoritativePublicKey,proto3" json:"authoritativePublicKey,omitempty"`
	// the hostPublicKey is the ephemeral public key
	HostPublicKey []byte `protobuf:"bytes,4,opt,name=hostPublicKey,proto3" json:"hostPublicKey,omitempty"`
	// hostPublicKeySignature is the signature of the authoratative key signing the hostPublicKey
	HostPublicKeySignature []byte `protobuf:"bytes,5,opt,name=hostPublicKeySignature,proto3" json:"hostPublicKeySignature,omitempty"`
	// serialized version of the addressAllocation message
	Message []byte `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	// the resultant signature
	MessageSignature     []byte   `protobuf:"bytes,7,opt,name=messageSignature,proto3" json:"messageSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedAddressAllocation) Reset()         { *m = SignedAddressAllocation{} }
func (m *SignedAddressAllocation) String() string { return proto.CompactTextString(m) }
func (*SignedAddressAllocation) ProtoMessage()    {}
func (*SignedAddressAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{12}
}

func (m *SignedAddressAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedAddressAllocation.Unmarshal(m, b)
}
func (m *SignedAddressAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedAddressAllocation.Marshal(b, m, deterministic)
}
func (m *SignedAddressAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedAddressAllocation.Merge(m, src)
}
func (m *SignedAddressAllocation) XXX_Size() int {
	return xxx_messageInfo_SignedAddressAllocation.Size(m)
}
func (m *SignedAddressAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedAddressAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_SignedAddressAllocation proto.InternalMessageInfo

func (m *SignedAddressAllocation) GetAddressAllocation() *AddressAllocation {
	if m != nil {
		return m.AddressAllocation
	}
	return nil
}

// Deprecated: Do not use.
func (m *SignedAddressAllocation) GetSignedAddressAllocation() []byte {
	if m != nil {
		return m.SignedAddressAllocation
	}
	return nil
}

func (m *SignedAddressAllocation) GetAuthoritativePublicKey() []byte {
	if m != nil {
		return m.AuthoritativePublicKey
	}
	return nil
}

func (m *SignedAddressAllocation) GetHostPublicKey() []byte {
	if m != nil {
		return m.HostPublicKey
	}
	return nil
}

func (m *SignedAddressAllocation) GetHostPublicKeySignature() []byte {
	if m != nil {
		return m.HostPublicKeySignature
	}
	return nil
}

func (m *SignedAddressAllocation) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedAddressAllocation) GetMessageSignature() []byte {
	if m != nil {
		return m.MessageSignature
	}
	return nil
}

// Data record type independent metadata information.
type DataRecordMetadata struct {
	// Description of why new version of the data was created.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Identification of the person who changed the data.
	CallMetadata *CallMetadata `protobuf:"bytes,2,opt,name=callMetadata,proto3" json:"callMetadata,omitempty"`
	// Time of change.
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRecordMetadata) Reset()         { *m = DataRecordMetadata{} }
func (m *DataRecordMetadata) String() string { return proto.CompactTextString(m) }
func (*DataRecordMetadata) ProtoMessage()    {}
func (*DataRecordMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a2977ef6488463b, []int{13}
}

func (m *DataRecordMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRecordMetadata.Unmarshal(m, b)
}
func (m *DataRecordMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRecordMetadata.Marshal(b, m, deterministic)
}
func (m *DataRecordMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRecordMetadata.Merge(m, src)
}
func (m *DataRecordMetadata) XXX_Size() int {
	return xxx_messageInfo_DataRecordMetadata.Size(m)
}
func (m *DataRecordMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRecordMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DataRecordMetadata proto.InternalMessageInfo

func (m *DataRecordMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DataRecordMetadata) GetCallMetadata() *CallMetadata {
	if m != nil {
		return m.CallMetadata
	}
	return nil
}

func (m *DataRecordMetadata) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("com.netflix.titus.Tier", Tier_name, Tier_value)
	proto.RegisterEnum("com.netflix.titus.Level", Level_name, Level_value)
	proto.RegisterEnum("com.netflix.titus.MountPerm", MountPerm_name, MountPerm_value)
	proto.RegisterEnum("com.netflix.titus.Day", Day_name, Day_value)
	proto.RegisterEnum("com.netflix.titus.CallMetadata_CallerType", CallMetadata_CallerType_name, CallMetadata_CallerType_value)
	proto.RegisterType((*CallMetadata)(nil), "com.netflix.titus.CallMetadata")
	proto.RegisterType((*CallMetadata_Caller)(nil), "com.netflix.titus.CallMetadata.Caller")
	proto.RegisterMapType((map[string]string)(nil), "com.netflix.titus.CallMetadata.Caller.ContextEntry")
	proto.RegisterType((*Page)(nil), "com.netflix.titus.Page")
	proto.RegisterType((*Pagination)(nil), "com.netflix.titus.Pagination")
	proto.RegisterType((*RetryPolicy)(nil), "com.netflix.titus.RetryPolicy")
	proto.RegisterType((*RetryPolicy_Immediate)(nil), "com.netflix.titus.RetryPolicy.Immediate")
	proto.RegisterType((*RetryPolicy_Delayed)(nil), "com.netflix.titus.RetryPolicy.Delayed")
	proto.RegisterType((*RetryPolicy_ExponentialBackOff)(nil), "com.netflix.titus.RetryPolicy.ExponentialBackOff")
	proto.RegisterType((*TokenBucketPolicy)(nil), "com.netflix.titus.TokenBucketPolicy")
	proto.RegisterType((*TokenBucketPolicy_FixedIntervalRefillStrategy)(nil), "com.netflix.titus.TokenBucketPolicy.FixedIntervalRefillStrategy")
	proto.RegisterType((*Reference)(nil), "com.netflix.titus.Reference")
	proto.RegisterType((*Reference_System)(nil), "com.netflix.titus.Reference.System")
	proto.RegisterType((*ResourceDimension)(nil), "com.netflix.titus.ResourceDimension")
	proto.RegisterType((*TimeWindow)(nil), "com.netflix.titus.TimeWindow")
	proto.RegisterType((*TimeWindow_HourlyTimeWindow)(nil), "com.netflix.titus.TimeWindow.HourlyTimeWindow")
	proto.RegisterType((*ContainerHealthProvider)(nil), "com.netflix.titus.ContainerHealthProvider")
	proto.RegisterMapType((map[string]string)(nil), "com.netflix.titus.ContainerHealthProvider.AttributesEntry")
	proto.RegisterType((*AddressLocation)(nil), "com.netflix.titus.AddressLocation")
	proto.RegisterType((*AddressAllocation)(nil), "com.netflix.titus.AddressAllocation")
	proto.RegisterType((*StaticIPAddressIDs)(nil), "com.netflix.titus.StaticIPAddressIDs")
	proto.RegisterType((*SignedAddressAllocation)(nil), "com.netflix.titus.SignedAddressAllocation")
	proto.RegisterType((*DataRecordMetadata)(nil), "com.netflix.titus.DataRecordMetadata")
}

func init() {
	proto.RegisterFile("netflix/titus/titus_base.proto", fileDescriptor_3a2977ef6488463b)
}

var fileDescriptor_3a2977ef6488463b = []byte{
	// 1586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x6e, 0x23, 0x49,
	0x15, 0x76, 0xfb, 0x2f, 0xf1, 0x71, 0x92, 0x71, 0x4a, 0x90, 0x31, 0x5e, 0x34, 0x1b, 0x79, 0x97,
	0x51, 0x14, 0x09, 0x8f, 0xc8, 0x2e, 0x08, 0x46, 0x2c, 0xda, 0x71, 0xb2, 0x83, 0xbd, 0x8c, 0x19,
	0xab, 0x92, 0x55, 0xa4, 0xd1, 0x02, 0x2a, 0x77, 0x9f, 0x38, 0x85, 0xdb, 0xdd, 0xa6, 0xba, 0x3a,
	0x93, 0xe6, 0x1a, 0xc1, 0x15, 0xe2, 0x9a, 0x4b, 0xde, 0x86, 0x97, 0xe0, 0x06, 0xc4, 0x0d, 0x0f,
	0x81, 0xd0, 0xa9, 0xaa, 0xb6, 0x3b, 0xb1, 0xb3, 0x33, 0xdc, 0xd8, 0xf5, 0x9d, 0xdf, 0xef, 0x9c,
	0xfa, 0x6d, 0x78, 0x12, 0xa1, 0xbe, 0x0a, 0xe5, 0xed, 0x33, 0x2d, 0x75, 0x9a, 0xd8, 0xdf, 0xdf,
	0x4c, 0x44, 0x82, 0xbd, 0x85, 0x8a, 0x75, 0xcc, 0xf6, 0xfd, 0x78, 0xde, 0x73, 0x36, 0x3d, 0xa3,
	0xed, 0x7c, 0x67, 0x1a, 0xc7, 0xd3, 0x10, 0x9f, 0x19, 0x83, 0x49, 0x7a, 0xf5, 0x4c, 0x44, 0x99,
	0xb5, 0xee, 0xfe, 0xb3, 0x02, 0x3b, 0xa7, 0x22, 0x0c, 0x47, 0xa8, 0x45, 0x20, 0xb4, 0x60, 0x4f,
	0x60, 0xdb, 0x17, 0x61, 0x88, 0x6a, 0x18, 0xb4, 0xbd, 0x43, 0xef, 0xa8, 0xd1, 0x2f, 0xb7, 0x3d,
	0xbe, 0x94, 0xb1, 0xcf, 0x61, 0xcb, 0x8e, 0x93, 0x76, 0xed, 0xb0, 0x72, 0xd4, 0x3c, 0x79, 0xda,
	0x5b, 0x4b, 0xd8, 0x2b, 0x46, 0x34, 0x00, 0x15, 0xcf, 0xdd, 0xd8, 0x13, 0x00, 0x1a, 0x72, 0x14,
	0x49, 0x1c, 0xb5, 0xcb, 0x94, 0x83, 0x17, 0x24, 0x39, 0x83, 0xb1, 0xd0, 0xd7, 0xed, 0xca, 0x61,
	0xa5, 0xc8, 0x80, 0x64, 0xec, 0x5b, 0x50, 0x0b, 0x70, 0x92, 0x4e, 0xdb, 0xd5, 0x43, 0xef, 0x68,
	0x9b, 0x5b, 0xd0, 0xf9, 0x97, 0x07, 0x75, 0x9b, 0x89, 0xed, 0x41, 0x59, 0x3a, 0xf2, 0xbc, 0x2c,
	0x03, 0xf6, 0x33, 0xa8, 0xea, 0x6c, 0x81, 0x26, 0xd5, 0xde, 0xc9, 0xf1, 0xfb, 0xf1, 0xbd, 0xc8,
	0x16, 0xc8, 0x8d, 0x1f, 0x1b, 0xc1, 0x96, 0x1f, 0x47, 0x1a, 0x6f, 0xb5, 0xe1, 0xd3, 0x3c, 0xf9,
	0xe4, 0xfd, 0x42, 0xf4, 0x4e, 0xad, 0xd7, 0x17, 0x91, 0x56, 0x19, 0xcf, 0x63, 0x74, 0x9e, 0xc3,
	0x4e, 0x51, 0xc1, 0x5a, 0x50, 0x99, 0x61, 0xe6, 0xf8, 0xd2, 0x90, 0x2a, 0xbc, 0x11, 0x61, 0x8a,
	0xae, 0x39, 0x16, 0x3c, 0x2f, 0xff, 0xd8, 0xeb, 0x7e, 0x0a, 0xb0, 0xa2, 0xc7, 0x9a, 0xb0, 0xf5,
	0x55, 0x34, 0x8b, 0xe2, 0xb7, 0x51, 0xab, 0xc4, 0x1e, 0x41, 0xf3, 0xc5, 0x62, 0x11, 0x4a, 0x5f,
	0x68, 0x19, 0x47, 0x2d, 0x8f, 0x6d, 0x43, 0xf5, 0xab, 0x04, 0x55, 0xab, 0xdc, 0xfd, 0x35, 0x54,
	0xc7, 0x62, 0x8a, 0xac, 0x0b, 0xb0, 0x10, 0x53, 0xfc, 0x65, 0x3a, 0x9f, 0xa0, 0x32, 0x09, 0x6b,
	0xa6, 0xb7, 0x05, 0x29, 0xeb, 0xc0, 0x36, 0xa1, 0x73, 0xf9, 0x7b, 0x9b, 0xbe, 0xc6, 0x97, 0x98,
	0x1d, 0x40, 0xdd, 0x4f, 0x55, 0x12, 0xab, 0x76, 0xc5, 0x10, 0x73, 0xa8, 0xfb, 0x6f, 0x0f, 0x60,
	0x2c, 0xa6, 0x32, 0x32, 0xa9, 0xd9, 0x4f, 0xa0, 0xe9, 0xa7, 0x4a, 0x61, 0xa4, 0x29, 0xab, 0xc9,
	0xd3, 0x3c, 0x79, 0xbc, 0xa1, 0x67, 0xa4, 0xe6, 0x45, 0x5b, 0xd6, 0x86, 0xad, 0x6b, 0x91, 0x8c,
	0x62, 0x65, 0x93, 0x6f, 0xf3, 0x1c, 0x12, 0x77, 0x1d, 0x6b, 0x11, 0x92, 0x59, 0x62, 0xf2, 0x3b,
	0xee, 0x2b, 0x29, 0xad, 0x2c, 0x83, 0x86, 0x1a, 0xe7, 0x89, 0x59, 0x1e, 0x35, 0x5e, 0x90, 0x14,
	0xf8, 0xd7, 0x8a, 0xfc, 0xd9, 0x53, 0xd8, 0xb3, 0xa3, 0x71, 0x9c, 0x48, 0x2a, 0xa1, 0x5d, 0x37,
	0xbe, 0xf7, 0xa4, 0xdd, 0xbf, 0x55, 0xa1, 0xc9, 0x51, 0xab, 0x6c, 0x1c, 0x87, 0xd2, 0xcf, 0xd8,
	0x00, 0x1a, 0x72, 0x3e, 0xc7, 0x40, 0x0a, 0x9d, 0x97, 0x79, 0xb4, 0xa1, 0xcc, 0x82, 0x4b, 0x6f,
	0x98, 0xdb, 0x0f, 0x4a, 0x7c, 0xe5, 0xcc, 0xfa, 0xb0, 0x15, 0x60, 0x28, 0x32, 0x0c, 0x4c, 0xdd,
	0x9b, 0x77, 0x55, 0x31, 0xce, 0x99, 0xb5, 0x1e, 0x94, 0x78, 0xee, 0xc8, 0x7c, 0x60, 0x78, 0xbb,
	0x88, 0x23, 0x8c, 0xb4, 0x14, 0x61, 0x5f, 0xf8, 0xb3, 0xd7, 0x57, 0x57, 0xa6, 0x53, 0xcd, 0x93,
	0x1f, 0xbc, 0x23, 0xdc, 0x17, 0x6b, 0x8e, 0x83, 0x12, 0xdf, 0x10, 0xae, 0xf3, 0x3d, 0x68, 0x2c,
	0x4b, 0xa0, 0xd9, 0x52, 0xa8, 0x95, 0xc4, 0xc4, 0x54, 0xbf, 0xcb, 0x73, 0xd8, 0x41, 0xd8, 0x72,
	0x0c, 0xa9, 0xb9, 0x32, 0x92, 0x14, 0xc3, 0x48, 0x46, 0xd6, 0xb6, 0xca, 0xef, 0x49, 0x29, 0x58,
	0xe0, 0x0c, 0xca, 0xc6, 0x20, 0x87, 0xc5, 0x34, 0x95, 0xbb, 0x69, 0xfe, 0xe8, 0x01, 0x5b, 0xa7,
	0xfe, 0xde, 0x29, 0x7b, 0xc0, 0xe6, 0xe2, 0xd6, 0xa0, 0x61, 0xa4, 0x51, 0xdd, 0x88, 0x70, 0x99,
	0x7d, 0x83, 0xe6, 0x61, 0x22, 0xfd, 0x6d, 0xa8, 0xdb, 0x4e, 0x76, 0xff, 0x51, 0x86, 0xfd, 0x8b,
	0x78, 0x86, 0x51, 0x3f, 0xf5, 0x67, 0xa8, 0xdd, 0x4a, 0xe9, 0xd0, 0x99, 0xb6, 0x10, 0xbe, 0xd4,
	0x99, 0xe3, 0xb2, 0xc4, 0xec, 0x53, 0xf8, 0xb6, 0xe3, 0x65, 0xb7, 0xe0, 0xeb, 0x2b, 0xe3, 0x9f,
	0x13, 0xd9, 0xac, 0x64, 0x7f, 0xf0, 0xe0, 0x83, 0x2b, 0x79, 0x8b, 0x41, 0xce, 0x8f, 0xe3, 0x95,
	0x0c, 0xc3, 0x73, 0xad, 0x84, 0xc6, 0x69, 0xe6, 0xe6, 0xfd, 0xf3, 0x0d, 0xf3, 0xbe, 0xc6, 0xae,
	0xf7, 0xf2, 0xe1, 0x38, 0x83, 0x12, 0xff, 0xa6, 0x34, 0x9d, 0x5f, 0xc1, 0x07, 0xdf, 0xe0, 0x4d,
	0x3b, 0x52, 0x19, 0x09, 0xa7, 0x2d, 0x52, 0x31, 0x05, 0x15, 0x24, 0xa4, 0x97, 0xab, 0xce, 0x57,
	0xad, 0x7e, 0x25, 0xe9, 0xb7, 0x60, 0xef, 0x6e, 0xc4, 0xee, 0x7f, 0x3c, 0x68, 0x70, 0xbc, 0x42,
	0x85, 0x91, 0x8f, 0xec, 0x33, 0xa8, 0x27, 0x59, 0xa2, 0x71, 0xee, 0xb6, 0xdf, 0x47, 0x1b, 0xd7,
	0xb9, 0xb3, 0xee, 0x9d, 0x1b, 0xd3, 0x41, 0x89, 0x3b, 0x27, 0xf6, 0x7d, 0xa8, 0x6a, 0x89, 0xca,
	0xdd, 0x0c, 0x9b, 0x8e, 0xa8, 0x0b, 0x89, 0x6a, 0x50, 0xe2, 0xc6, 0x8c, 0x3d, 0x85, 0xdd, 0x7c,
	0xd6, 0x7e, 0xae, 0xe2, 0x74, 0x61, 0x8f, 0xc1, 0x41, 0x89, 0xdf, 0x15, 0xb3, 0x03, 0xa8, 0xfd,
	0x36, 0x9e, 0x0c, 0x03, 0x53, 0x10, 0xe9, 0x2d, 0x64, 0x6d, 0xa8, 0x6b, 0x91, 0xcc, 0x86, 0x81,
	0x3d, 0x7f, 0x88, 0x88, 0xc5, 0x9d, 0x6d, 0xa8, 0x5b, 0x72, 0xfd, 0x66, 0xa1, 0xbc, 0xee, 0x9f,
	0x3d, 0xd8, 0xe7, 0x98, 0xc4, 0xa9, 0xf2, 0xf1, 0x4c, 0xce, 0x31, 0x4a, 0xe8, 0x7c, 0x6d, 0x41,
	0xc5, 0x5f, 0xa4, 0x6e, 0xcb, 0xd1, 0x90, 0x24, 0xd3, 0x45, 0x6a, 0xca, 0xd8, 0xe5, 0x34, 0xa4,
	0x05, 0x37, 0xc7, 0x79, 0xac, 0xb2, 0x51, 0xdf, 0xad, 0xd5, 0x25, 0xa6, 0x63, 0x30, 0x90, 0xc9,
	0x6c, 0xd4, 0x37, 0xfc, 0x76, 0xb9, 0x43, 0xec, 0x10, 0x9a, 0x11, 0xea, 0xb7, 0xb1, 0x9a, 0x8d,
	0x26, 0x8b, 0xc4, 0x70, 0xdc, 0xe5, 0x45, 0x51, 0xf7, 0xbf, 0x1e, 0xc0, 0x85, 0x9c, 0xe3, 0xa5,
	0x8c, 0x82, 0xf8, 0x2d, 0x3b, 0x86, 0x6a, 0x20, 0x32, 0xda, 0x5d, 0x95, 0xa3, 0xbd, 0x93, 0x83,
	0x0d, 0xed, 0x3b, 0x13, 0x19, 0x37, 0x36, 0xec, 0x6b, 0xd8, 0xbf, 0x8e, 0x53, 0x15, 0x66, 0x2b,
	0x7f, 0x5a, 0xe1, 0x74, 0x9d, 0xf6, 0x36, 0xf6, 0x3d, 0xb7, 0xea, 0x0d, 0xee, 0xb9, 0xf1, 0xf5,
	0x40, 0x54, 0xae, 0x96, 0x73, 0x7c, 0x13, 0x47, 0xe8, 0xee, 0xa6, 0x25, 0xee, 0x7c, 0x09, 0xad,
	0xfb, 0x21, 0xd8, 0x77, 0xa1, 0x91, 0x68, 0xa1, 0x34, 0x29, 0x5c, 0x23, 0x57, 0x02, 0xda, 0xe7,
	0x18, 0x05, 0x46, 0x67, 0x5b, 0x9a, 0xc3, 0xee, 0xdf, 0x3d, 0x78, 0x4c, 0x97, 0xb7, 0x90, 0x11,
	0xaa, 0x01, 0x8a, 0x50, 0x5f, 0x8f, 0x55, 0x7c, 0x23, 0x03, 0x54, 0x8c, 0x41, 0x35, 0x12, 0x73,
	0x74, 0x17, 0xb9, 0x19, 0xb3, 0x37, 0x00, 0x42, 0x6b, 0x25, 0x27, 0xa9, 0x36, 0x87, 0x06, 0x95,
	0xfb, 0x7c, 0xd3, 0xeb, 0x61, 0x73, 0xcc, 0xde, 0x8b, 0xa5, 0xb3, 0x7d, 0x44, 0x14, 0xa2, 0x75,
	0x3e, 0x83, 0x47, 0xf7, 0xd4, 0xff, 0xd7, 0x53, 0xe2, 0x77, 0xf0, 0xe8, 0x45, 0x10, 0x28, 0x4c,
	0x92, 0x57, 0xb1, 0x7d, 0x33, 0xd0, 0xc2, 0x50, 0x38, 0xa5, 0xfb, 0xcf, 0x46, 0x70, 0x88, 0x1d,
	0x43, 0x4b, 0xdc, 0x08, 0x19, 0x8a, 0x89, 0x0c, 0xa5, 0xce, 0x4c, 0x97, 0x6d, 0xbc, 0x35, 0x39,
	0xcd, 0x44, 0x92, 0x4e, 0x22, 0xd4, 0xc3, 0x20, 0x9f, 0x89, 0x1c, 0x77, 0xff, 0xe2, 0xc1, 0xbe,
	0xcb, 0xf9, 0x22, 0x0c, 0xf3, 0xac, 0xaf, 0xe0, 0x91, 0xb8, 0x4b, 0xc4, 0x6d, 0xe6, 0xee, 0x86,
	0x46, 0xdd, 0xa3, 0xcc, 0xef, 0xbb, 0xd2, 0x2c, 0xa4, 0xa9, 0x0c, 0x1c, 0x3f, 0x33, 0xa6, 0xf9,
	0x74, 0x66, 0x8e, 0x52, 0x0e, 0xbb, 0xc7, 0xc0, 0xce, 0xb5, 0xd0, 0xd2, 0x1f, 0x8e, 0x5d, 0xe4,
	0xe1, 0x59, 0x42, 0x4d, 0x23, 0x3f, 0xbb, 0xb0, 0x1b, 0xdc, 0x82, 0xee, 0x9f, 0x2a, 0xf0, 0xf8,
	0x5c, 0x4e, 0x23, 0x0c, 0xd6, 0x6b, 0xe0, 0xb0, 0x2f, 0xee, 0x0b, 0x5d, 0x15, 0x1f, 0x3f, 0x5c,
	0xc5, 0xca, 0x96, 0xaf, 0xbb, 0xb3, 0x9f, 0xc2, 0xe3, 0x64, 0x73, 0x3a, 0x53, 0xdc, 0x8e, 0x79,
	0xfe, 0x3c, 0x64, 0xc2, 0x7e, 0x04, 0x07, 0x22, 0xd5, 0xd7, 0xb1, 0x92, 0x54, 0xdf, 0x0d, 0x8e,
	0xd3, 0x49, 0x28, 0xfd, 0x5f, 0xa0, 0xbd, 0x19, 0x76, 0xf8, 0x03, 0x5a, 0xf6, 0x31, 0xec, 0x5e,
	0xc7, 0x89, 0x5e, 0x99, 0x57, 0x8d, 0xf9, 0x5d, 0x21, 0x45, 0xbf, 0x23, 0xa0, 0xbe, 0x08, 0x9d,
	0x2a, 0x34, 0xa7, 0xc6, 0x0e, 0x7f, 0x40, 0x4b, 0x33, 0x31, 0xc7, 0x24, 0xa1, 0x67, 0x61, 0xdd,
	0x18, 0xe6, 0x90, 0xd6, 0x98, 0x1b, 0xae, 0x62, 0x6d, 0x19, 0x93, 0x35, 0x79, 0xf7, 0xaf, 0x1e,
	0xb0, 0x33, 0xa1, 0x05, 0x47, 0x3f, 0x56, 0xc1, 0xf2, 0xd3, 0xe5, 0x10, 0x9a, 0x01, 0x26, 0xbe,
	0x92, 0x0b, 0xbd, 0x5a, 0xc3, 0x45, 0x11, 0x3b, 0x85, 0x1d, 0xbf, 0xf0, 0x4e, 0x77, 0x6f, 0xad,
	0x0f, 0xdf, 0xf1, 0x9c, 0xe7, 0x77, 0x9c, 0xe8, 0xec, 0xa0, 0xb3, 0x25, 0xd1, 0x62, 0xbe, 0x70,
	0x57, 0xda, 0x4a, 0x70, 0xfc, 0x04, 0xaa, 0x74, 0x67, 0xd0, 0xeb, 0xfb, 0x65, 0x88, 0xb7, 0xad,
	0x12, 0xdb, 0x81, 0xed, 0x53, 0x25, 0xb5, 0xf4, 0x45, 0xd8, 0xf2, 0x8e, 0xbf, 0x86, 0xda, 0x2b,
	0xbc, 0xc1, 0x90, 0xde, 0xeb, 0xf6, 0xc8, 0x37, 0xb0, 0x55, 0x62, 0xbb, 0xd0, 0x20, 0x4f, 0x0b,
	0x3d, 0x76, 0x00, 0xec, 0xb4, 0x78, 0xab, 0x58, 0x79, 0x99, 0xc2, 0x7d, 0x19, 0x4f, 0x2c, 0xaa,
	0x18, 0x27, 0x91, 0xcc, 0x2c, 0xac, 0x1e, 0x7f, 0x04, 0x8d, 0x51, 0x9c, 0x46, 0x7a, 0x8c, 0x6a,
	0xce, 0xea, 0x50, 0xe6, 0xaf, 0x5b, 0x25, 0xfa, 0xbf, 0x7c, 0xdd, 0xf2, 0x0c, 0xbe, 0x6c, 0x95,
	0x8f, 0x05, 0x54, 0xce, 0x44, 0xc6, 0x00, 0xea, 0xa3, 0x38, 0x0a, 0x44, 0xd6, 0x2a, 0xd1, 0x97,
	0xc4, 0x45, 0x8a, 0x09, 0x01, 0x8f, 0x62, 0x5e, 0x62, 0x10, 0x59, 0x68, 0x12, 0x5e, 0x5c, 0xa7,
	0xca, 0xa0, 0x0a, 0x79, 0xbd, 0x54, 0x92, 0xc6, 0x55, 0xd2, 0x9c, 0xd3, 0x8c, 0x10, 0xaa, 0x91,
	0xe6, 0x3c, 0x35, 0xf1, 0xea, 0xfd, 0x1f, 0xc2, 0x87, 0xeb, 0x3d, 0x9d, 0xaa, 0x85, 0x6f, 0x3f,
	0x3b, 0xa7, 0x18, 0xf5, 0x1b, 0x17, 0x24, 0xec, 0x8b, 0x04, 0xc7, 0xde, 0x9b, 0x9a, 0xb1, 0x98,
	0xd4, 0x8d, 0xf6, 0x93, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xdd, 0x22, 0x59, 0xe4, 0x0e,
	0x00, 0x00,
}
