// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netflix/titus/titus_agent_api.proto

package titus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Agent instance deployment state.
type InstanceLifecycleState int32

const (
	// Initial state of an agent, set when first discovered.
	InstanceLifecycleState_StartInitiated InstanceLifecycleState = 0
	// / An agent instance can move to this state only from the 'StartInitiated' state. This happens as soon as all
	//  healthcheck indicators for the agent are ok. At this point, the agent can accept containers, provided
	//  that other criteria are fullfiled.
	InstanceLifecycleState_Started InstanceLifecycleState = 1
	// / An agent instance is terminating. No new work is accepted.
	InstanceLifecycleState_KillInitiated InstanceLifecycleState = 2
	// / An agent instance is not running anymore.
	InstanceLifecycleState_Stopped InstanceLifecycleState = 3
	// / An agent instance state is unknown.
	InstanceLifecycleState_InstanceStateUnknown InstanceLifecycleState = 4
)

var InstanceLifecycleState_name = map[int32]string{
	0: "StartInitiated",
	1: "Started",
	2: "KillInitiated",
	3: "Stopped",
	4: "InstanceStateUnknown",
}
var InstanceLifecycleState_value = map[string]int32{
	"StartInitiated":       0,
	"Started":              1,
	"KillInitiated":        2,
	"Stopped":              3,
	"InstanceStateUnknown": 4,
}

func (x InstanceLifecycleState) String() string {
	return proto.EnumName(InstanceLifecycleState_name, int32(x))
}
func (InstanceLifecycleState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{0}
}

// / An agent health state.
type HealthState int32

const (
	// / Health state is unknown.
	HealthState_Unknown HealthState = 0
	// / An agent is healthy.
	HealthState_Healthy HealthState = 1
	// / An agent is unhealthy.
	HealthState_Unhealthy HealthState = 2
)

var HealthState_name = map[int32]string{
	0: "Unknown",
	1: "Healthy",
	2: "Unhealthy",
}
var HealthState_value = map[string]int32{
	"Unknown":   0,
	"Healthy":   1,
	"Unhealthy": 2,
}

func (x HealthState) String() string {
	return proto.EnumName(HealthState_name, int32(x))
}
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{1}
}

// / Agent server group lifecycle state.
type InstanceGroupLifecycleState int32

const (
	// / Server group is not accepting any traffic or auto-scale actions.
	InstanceGroupLifecycleState_Inactive InstanceGroupLifecycleState = 0
	// / Server group is open for traffic, and auto-scaling.
	InstanceGroupLifecycleState_Active InstanceGroupLifecycleState = 1
	// / Server group is open for traffic, and auto-scaling, but other server groups are preferred.
	InstanceGroupLifecycleState_PhasedOut InstanceGroupLifecycleState = 2
	// / Server group is not accepting any traffic. All idle instances will be terminated.
	InstanceGroupLifecycleState_Removable InstanceGroupLifecycleState = 3
)

var InstanceGroupLifecycleState_name = map[int32]string{
	0: "Inactive",
	1: "Active",
	2: "PhasedOut",
	3: "Removable",
}
var InstanceGroupLifecycleState_value = map[string]int32{
	"Inactive":  0,
	"Active":    1,
	"PhasedOut": 2,
	"Removable": 3,
}

func (x InstanceGroupLifecycleState) String() string {
	return proto.EnumName(InstanceGroupLifecycleState_name, int32(x))
}
func (InstanceGroupLifecycleState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{2}
}

// / Agent instance deployment status.
type InstanceLifecycleStatus struct {
	// / Agent instance state.
	State InstanceLifecycleState `protobuf:"varint,1,opt,name=state,proto3,enum=com.netflix.titus.InstanceLifecycleState" json:"state,omitempty"`
	// / Instance launch timestamp (EC2 API provides only launch time, with no information about time of subsequent state changes).
	LaunchTimestamp      uint64   `protobuf:"varint,3,opt,name=launchTimestamp,proto3" json:"launchTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceLifecycleStatus) Reset()         { *m = InstanceLifecycleStatus{} }
func (m *InstanceLifecycleStatus) String() string { return proto.CompactTextString(m) }
func (*InstanceLifecycleStatus) ProtoMessage()    {}
func (*InstanceLifecycleStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{0}
}
func (m *InstanceLifecycleStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceLifecycleStatus.Unmarshal(m, b)
}
func (m *InstanceLifecycleStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceLifecycleStatus.Marshal(b, m, deterministic)
}
func (dst *InstanceLifecycleStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceLifecycleStatus.Merge(dst, src)
}
func (m *InstanceLifecycleStatus) XXX_Size() int {
	return xxx_messageInfo_InstanceLifecycleStatus.Size(m)
}
func (m *InstanceLifecycleStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceLifecycleStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceLifecycleStatus proto.InternalMessageInfo

func (m *InstanceLifecycleStatus) GetState() InstanceLifecycleState {
	if m != nil {
		return m.State
	}
	return InstanceLifecycleState_StartInitiated
}

func (m *InstanceLifecycleStatus) GetLaunchTimestamp() uint64 {
	if m != nil {
		return m.LaunchTimestamp
	}
	return 0
}

// / Agent health status.
type HealthStatus struct {
	// / Source id
	SourceId string `protobuf:"bytes,1,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	// / Agent health state.
	State HealthState `protobuf:"varint,2,opt,name=state,proto3,enum=com.netflix.titus.HealthState" json:"state,omitempty"`
	// / If agent is in bad state, contains more information about the problem.
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// / Time at which an agent went into the given state.
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// / Health status from individual components, which this state aggregates.
	Components           []*HealthStatus `protobuf:"bytes,5,rep,name=components,proto3" json:"components,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HealthStatus) Reset()         { *m = HealthStatus{} }
func (m *HealthStatus) String() string { return proto.CompactTextString(m) }
func (*HealthStatus) ProtoMessage()    {}
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{1}
}
func (m *HealthStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthStatus.Unmarshal(m, b)
}
func (m *HealthStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthStatus.Marshal(b, m, deterministic)
}
func (dst *HealthStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthStatus.Merge(dst, src)
}
func (m *HealthStatus) XXX_Size() int {
	return xxx_messageInfo_HealthStatus.Size(m)
}
func (m *HealthStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthStatus.DiscardUnknown(m)
}

var xxx_messageInfo_HealthStatus proto.InternalMessageInfo

func (m *HealthStatus) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *HealthStatus) GetState() HealthState {
	if m != nil {
		return m.State
	}
	return HealthState_Unknown
}

func (m *HealthStatus) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *HealthStatus) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HealthStatus) GetComponents() []*HealthStatus {
	if m != nil {
		return m.Components
	}
	return nil
}

// / Agent server group status.
type InstanceGroupLifecycleStatus struct {
	// / Lifecycle state.
	State InstanceGroupLifecycleState `protobuf:"varint,1,opt,name=state,proto3,enum=com.netflix.titus.InstanceGroupLifecycleState" json:"state,omitempty"`
	// / A reason for moving into this state.
	Detail string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	// / Time at which agent server group went into the given state.
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceGroupLifecycleStatus) Reset()         { *m = InstanceGroupLifecycleStatus{} }
func (m *InstanceGroupLifecycleStatus) String() string { return proto.CompactTextString(m) }
func (*InstanceGroupLifecycleStatus) ProtoMessage()    {}
func (*InstanceGroupLifecycleStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{2}
}
func (m *InstanceGroupLifecycleStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGroupLifecycleStatus.Unmarshal(m, b)
}
func (m *InstanceGroupLifecycleStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGroupLifecycleStatus.Marshal(b, m, deterministic)
}
func (dst *InstanceGroupLifecycleStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGroupLifecycleStatus.Merge(dst, src)
}
func (m *InstanceGroupLifecycleStatus) XXX_Size() int {
	return xxx_messageInfo_InstanceGroupLifecycleStatus.Size(m)
}
func (m *InstanceGroupLifecycleStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGroupLifecycleStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGroupLifecycleStatus proto.InternalMessageInfo

func (m *InstanceGroupLifecycleStatus) GetState() InstanceGroupLifecycleState {
	if m != nil {
		return m.State
	}
	return InstanceGroupLifecycleState_Inactive
}

func (m *InstanceGroupLifecycleStatus) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *InstanceGroupLifecycleStatus) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// / An agent server.
type AgentInstance struct {
	// / A unique id of the agent server.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// / A server group, to which the agent belongs to.
	InstanceGroupId string `protobuf:"bytes,2,opt,name=instanceGroupId,proto3" json:"instanceGroupId,omitempty"`
	// / IP address of the agent.
	IpAddress string `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	// / Hostname of the agent.
	Hostname string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// / Current deployment status.
	LifecycleStatus *InstanceLifecycleStatus `protobuf:"bytes,5,opt,name=lifecycleStatus,proto3" json:"lifecycleStatus,omitempty"`
	// / Current health status.
	HealthStatus *HealthStatus `protobuf:"bytes,6,opt,name=healthStatus,proto3" json:"healthStatus,omitempty"`
	// / Arbitrary set of key/value pairs. Keys starting with 'titus' prefix are reserved for Titus.
	Attributes           map[string]string `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AgentInstance) Reset()         { *m = AgentInstance{} }
func (m *AgentInstance) String() string { return proto.CompactTextString(m) }
func (*AgentInstance) ProtoMessage()    {}
func (*AgentInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{3}
}
func (m *AgentInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInstance.Unmarshal(m, b)
}
func (m *AgentInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInstance.Marshal(b, m, deterministic)
}
func (dst *AgentInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInstance.Merge(dst, src)
}
func (m *AgentInstance) XXX_Size() int {
	return xxx_messageInfo_AgentInstance.Size(m)
}
func (m *AgentInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInstance.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInstance proto.InternalMessageInfo

func (m *AgentInstance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AgentInstance) GetInstanceGroupId() string {
	if m != nil {
		return m.InstanceGroupId
	}
	return ""
}

func (m *AgentInstance) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *AgentInstance) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AgentInstance) GetLifecycleStatus() *InstanceLifecycleStatus {
	if m != nil {
		return m.LifecycleStatus
	}
	return nil
}

func (m *AgentInstance) GetHealthStatus() *HealthStatus {
	if m != nil {
		return m.HealthStatus
	}
	return nil
}

func (m *AgentInstance) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// / An agent instance group.
type AgentInstanceGroup struct {
	// / A unique id of the server group.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// / An id of the server type (for example AWS instance type id).
	InstanceType string `protobuf:"bytes,2,opt,name=instanceType,proto3" json:"instanceType,omitempty"`
	// / Instance resources (cpu, memory, etc).
	InstanceResources *ResourceDimension `protobuf:"bytes,3,opt,name=instanceResources,proto3" json:"instanceResources,omitempty"`
	// / Tier to which the given server group is attached.
	Tier Tier `protobuf:"varint,4,opt,name=tier,proto3,enum=com.netflix.titus.Tier" json:"tier,omitempty"`
	// / Minimum number of servers in the server group.
	Min uint32 `protobuf:"varint,5,opt,name=min,proto3" json:"min,omitempty"`
	// / Desired number of servers in the server group.
	Desired uint32 `protobuf:"varint,6,opt,name=desired,proto3" json:"desired,omitempty"`
	// / Current number of servers in the server group.
	Current uint32 `protobuf:"varint,7,opt,name=current,proto3" json:"current,omitempty"`
	// / Maximum number of servers in the server group.
	Max uint32 `protobuf:"varint,8,opt,name=max,proto3" json:"max,omitempty"`
	// / Set to true, if a new servers can be started in this server group.
	IsLaunchEnabled bool `protobuf:"varint,9,opt,name=isLaunchEnabled,proto3" json:"isLaunchEnabled,omitempty"`
	// / Set to true, if servers can be terminated in this server group.
	IsTerminateEnabled bool `protobuf:"varint,10,opt,name=isTerminateEnabled,proto3" json:"isTerminateEnabled,omitempty"`
	// / Current lifecycle state.
	LifecycleStatus *InstanceGroupLifecycleStatus `protobuf:"bytes,11,opt,name=lifecycleStatus,proto3" json:"lifecycleStatus,omitempty"`
	// / Time at wich the server group was created.
	LaunchTimestamp uint64 `protobuf:"varint,12,opt,name=launchTimestamp,proto3" json:"launchTimestamp,omitempty"`
	// / Arbitrary set of key/value pairs. Keys starting with 'titus' prefix are reserved for Titus.
	Attributes           map[string]string `protobuf:"bytes,13,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AgentInstanceGroup) Reset()         { *m = AgentInstanceGroup{} }
func (m *AgentInstanceGroup) String() string { return proto.CompactTextString(m) }
func (*AgentInstanceGroup) ProtoMessage()    {}
func (*AgentInstanceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{4}
}
func (m *AgentInstanceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInstanceGroup.Unmarshal(m, b)
}
func (m *AgentInstanceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInstanceGroup.Marshal(b, m, deterministic)
}
func (dst *AgentInstanceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInstanceGroup.Merge(dst, src)
}
func (m *AgentInstanceGroup) XXX_Size() int {
	return xxx_messageInfo_AgentInstanceGroup.Size(m)
}
func (m *AgentInstanceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInstanceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInstanceGroup proto.InternalMessageInfo

func (m *AgentInstanceGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AgentInstanceGroup) GetInstanceType() string {
	if m != nil {
		return m.InstanceType
	}
	return ""
}

func (m *AgentInstanceGroup) GetInstanceResources() *ResourceDimension {
	if m != nil {
		return m.InstanceResources
	}
	return nil
}

func (m *AgentInstanceGroup) GetTier() Tier {
	if m != nil {
		return m.Tier
	}
	return Tier_Flex
}

func (m *AgentInstanceGroup) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *AgentInstanceGroup) GetDesired() uint32 {
	if m != nil {
		return m.Desired
	}
	return 0
}

func (m *AgentInstanceGroup) GetCurrent() uint32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *AgentInstanceGroup) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *AgentInstanceGroup) GetIsLaunchEnabled() bool {
	if m != nil {
		return m.IsLaunchEnabled
	}
	return false
}

func (m *AgentInstanceGroup) GetIsTerminateEnabled() bool {
	if m != nil {
		return m.IsTerminateEnabled
	}
	return false
}

func (m *AgentInstanceGroup) GetLifecycleStatus() *InstanceGroupLifecycleStatus {
	if m != nil {
		return m.LifecycleStatus
	}
	return nil
}

func (m *AgentInstanceGroup) GetLaunchTimestamp() uint64 {
	if m != nil {
		return m.LaunchTimestamp
	}
	return 0
}

func (m *AgentInstanceGroup) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// / Events emitted for agent topology changes (new ASG created, new instance launched, etc).
type AgentChangeEvent struct {
	// Types that are valid to be assigned to Event:
	//	*AgentChangeEvent_InstanceGroupUpdate_
	//	*AgentChangeEvent_InstanceGroupRemoved_
	//	*AgentChangeEvent_AgentInstanceUpdate
	//	*AgentChangeEvent_AgentInstanceRemoved
	//	*AgentChangeEvent_SnapshotEnd_
	Event                isAgentChangeEvent_Event `protobuf_oneof:"Event"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AgentChangeEvent) Reset()         { *m = AgentChangeEvent{} }
func (m *AgentChangeEvent) String() string { return proto.CompactTextString(m) }
func (*AgentChangeEvent) ProtoMessage()    {}
func (*AgentChangeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{5}
}
func (m *AgentChangeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentChangeEvent.Unmarshal(m, b)
}
func (m *AgentChangeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentChangeEvent.Marshal(b, m, deterministic)
}
func (dst *AgentChangeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentChangeEvent.Merge(dst, src)
}
func (m *AgentChangeEvent) XXX_Size() int {
	return xxx_messageInfo_AgentChangeEvent.Size(m)
}
func (m *AgentChangeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentChangeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AgentChangeEvent proto.InternalMessageInfo

type isAgentChangeEvent_Event interface {
	isAgentChangeEvent_Event()
}

type AgentChangeEvent_InstanceGroupUpdate_ struct {
	InstanceGroupUpdate *AgentChangeEvent_InstanceGroupUpdate `protobuf:"bytes,1,opt,name=instanceGroupUpdate,proto3,oneof"`
}

type AgentChangeEvent_InstanceGroupRemoved_ struct {
	InstanceGroupRemoved *AgentChangeEvent_InstanceGroupRemoved `protobuf:"bytes,2,opt,name=instanceGroupRemoved,proto3,oneof"`
}

type AgentChangeEvent_AgentInstanceUpdate struct {
	AgentInstanceUpdate *AgentChangeEvent_InstanceUpdate `protobuf:"bytes,3,opt,name=agentInstanceUpdate,proto3,oneof"`
}

type AgentChangeEvent_AgentInstanceRemoved struct {
	AgentInstanceRemoved *AgentChangeEvent_InstanceRemoved `protobuf:"bytes,4,opt,name=agentInstanceRemoved,proto3,oneof"`
}

type AgentChangeEvent_SnapshotEnd_ struct {
	SnapshotEnd *AgentChangeEvent_SnapshotEnd `protobuf:"bytes,5,opt,name=snapshotEnd,proto3,oneof"`
}

func (*AgentChangeEvent_InstanceGroupUpdate_) isAgentChangeEvent_Event() {}

func (*AgentChangeEvent_InstanceGroupRemoved_) isAgentChangeEvent_Event() {}

func (*AgentChangeEvent_AgentInstanceUpdate) isAgentChangeEvent_Event() {}

func (*AgentChangeEvent_AgentInstanceRemoved) isAgentChangeEvent_Event() {}

func (*AgentChangeEvent_SnapshotEnd_) isAgentChangeEvent_Event() {}

func (m *AgentChangeEvent) GetEvent() isAgentChangeEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *AgentChangeEvent) GetInstanceGroupUpdate() *AgentChangeEvent_InstanceGroupUpdate {
	if x, ok := m.GetEvent().(*AgentChangeEvent_InstanceGroupUpdate_); ok {
		return x.InstanceGroupUpdate
	}
	return nil
}

func (m *AgentChangeEvent) GetInstanceGroupRemoved() *AgentChangeEvent_InstanceGroupRemoved {
	if x, ok := m.GetEvent().(*AgentChangeEvent_InstanceGroupRemoved_); ok {
		return x.InstanceGroupRemoved
	}
	return nil
}

func (m *AgentChangeEvent) GetAgentInstanceUpdate() *AgentChangeEvent_InstanceUpdate {
	if x, ok := m.GetEvent().(*AgentChangeEvent_AgentInstanceUpdate); ok {
		return x.AgentInstanceUpdate
	}
	return nil
}

func (m *AgentChangeEvent) GetAgentInstanceRemoved() *AgentChangeEvent_InstanceRemoved {
	if x, ok := m.GetEvent().(*AgentChangeEvent_AgentInstanceRemoved); ok {
		return x.AgentInstanceRemoved
	}
	return nil
}

func (m *AgentChangeEvent) GetSnapshotEnd() *AgentChangeEvent_SnapshotEnd {
	if x, ok := m.GetEvent().(*AgentChangeEvent_SnapshotEnd_); ok {
		return x.SnapshotEnd
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AgentChangeEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AgentChangeEvent_OneofMarshaler, _AgentChangeEvent_OneofUnmarshaler, _AgentChangeEvent_OneofSizer, []interface{}{
		(*AgentChangeEvent_InstanceGroupUpdate_)(nil),
		(*AgentChangeEvent_InstanceGroupRemoved_)(nil),
		(*AgentChangeEvent_AgentInstanceUpdate)(nil),
		(*AgentChangeEvent_AgentInstanceRemoved)(nil),
		(*AgentChangeEvent_SnapshotEnd_)(nil),
	}
}

func _AgentChangeEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AgentChangeEvent)
	// Event
	switch x := m.Event.(type) {
	case *AgentChangeEvent_InstanceGroupUpdate_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InstanceGroupUpdate); err != nil {
			return err
		}
	case *AgentChangeEvent_InstanceGroupRemoved_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InstanceGroupRemoved); err != nil {
			return err
		}
	case *AgentChangeEvent_AgentInstanceUpdate:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AgentInstanceUpdate); err != nil {
			return err
		}
	case *AgentChangeEvent_AgentInstanceRemoved:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AgentInstanceRemoved); err != nil {
			return err
		}
	case *AgentChangeEvent_SnapshotEnd_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SnapshotEnd); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AgentChangeEvent.Event has unexpected type %T", x)
	}
	return nil
}

func _AgentChangeEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AgentChangeEvent)
	switch tag {
	case 1: // Event.instanceGroupUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AgentChangeEvent_InstanceGroupUpdate)
		err := b.DecodeMessage(msg)
		m.Event = &AgentChangeEvent_InstanceGroupUpdate_{msg}
		return true, err
	case 2: // Event.instanceGroupRemoved
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AgentChangeEvent_InstanceGroupRemoved)
		err := b.DecodeMessage(msg)
		m.Event = &AgentChangeEvent_InstanceGroupRemoved_{msg}
		return true, err
	case 3: // Event.agentInstanceUpdate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AgentChangeEvent_InstanceUpdate)
		err := b.DecodeMessage(msg)
		m.Event = &AgentChangeEvent_AgentInstanceUpdate{msg}
		return true, err
	case 4: // Event.agentInstanceRemoved
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AgentChangeEvent_InstanceRemoved)
		err := b.DecodeMessage(msg)
		m.Event = &AgentChangeEvent_AgentInstanceRemoved{msg}
		return true, err
	case 5: // Event.snapshotEnd
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AgentChangeEvent_SnapshotEnd)
		err := b.DecodeMessage(msg)
		m.Event = &AgentChangeEvent_SnapshotEnd_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AgentChangeEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AgentChangeEvent)
	// Event
	switch x := m.Event.(type) {
	case *AgentChangeEvent_InstanceGroupUpdate_:
		s := proto.Size(x.InstanceGroupUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AgentChangeEvent_InstanceGroupRemoved_:
		s := proto.Size(x.InstanceGroupRemoved)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AgentChangeEvent_AgentInstanceUpdate:
		s := proto.Size(x.AgentInstanceUpdate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AgentChangeEvent_AgentInstanceRemoved:
		s := proto.Size(x.AgentInstanceRemoved)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AgentChangeEvent_SnapshotEnd_:
		s := proto.Size(x.SnapshotEnd)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// / Sent whenever 'AgentInstanceGroup' state changes, excluding agent instances.
type AgentChangeEvent_InstanceGroupUpdate struct {
	InstanceGroup        *AgentInstanceGroup `protobuf:"bytes,1,opt,name=instanceGroup,proto3" json:"instanceGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AgentChangeEvent_InstanceGroupUpdate) Reset()         { *m = AgentChangeEvent_InstanceGroupUpdate{} }
func (m *AgentChangeEvent_InstanceGroupUpdate) String() string { return proto.CompactTextString(m) }
func (*AgentChangeEvent_InstanceGroupUpdate) ProtoMessage()    {}
func (*AgentChangeEvent_InstanceGroupUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{5, 0}
}
func (m *AgentChangeEvent_InstanceGroupUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentChangeEvent_InstanceGroupUpdate.Unmarshal(m, b)
}
func (m *AgentChangeEvent_InstanceGroupUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentChangeEvent_InstanceGroupUpdate.Marshal(b, m, deterministic)
}
func (dst *AgentChangeEvent_InstanceGroupUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentChangeEvent_InstanceGroupUpdate.Merge(dst, src)
}
func (m *AgentChangeEvent_InstanceGroupUpdate) XXX_Size() int {
	return xxx_messageInfo_AgentChangeEvent_InstanceGroupUpdate.Size(m)
}
func (m *AgentChangeEvent_InstanceGroupUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentChangeEvent_InstanceGroupUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_AgentChangeEvent_InstanceGroupUpdate proto.InternalMessageInfo

func (m *AgentChangeEvent_InstanceGroupUpdate) GetInstanceGroup() *AgentInstanceGroup {
	if m != nil {
		return m.InstanceGroup
	}
	return nil
}

// / Sent whenever 'AgentInstanceGroup' is removed.
type AgentChangeEvent_InstanceGroupRemoved struct {
	InstanceGroupId      string   `protobuf:"bytes,1,opt,name=instanceGroupId,proto3" json:"instanceGroupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentChangeEvent_InstanceGroupRemoved) Reset()         { *m = AgentChangeEvent_InstanceGroupRemoved{} }
func (m *AgentChangeEvent_InstanceGroupRemoved) String() string { return proto.CompactTextString(m) }
func (*AgentChangeEvent_InstanceGroupRemoved) ProtoMessage()    {}
func (*AgentChangeEvent_InstanceGroupRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{5, 1}
}
func (m *AgentChangeEvent_InstanceGroupRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentChangeEvent_InstanceGroupRemoved.Unmarshal(m, b)
}
func (m *AgentChangeEvent_InstanceGroupRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentChangeEvent_InstanceGroupRemoved.Marshal(b, m, deterministic)
}
func (dst *AgentChangeEvent_InstanceGroupRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentChangeEvent_InstanceGroupRemoved.Merge(dst, src)
}
func (m *AgentChangeEvent_InstanceGroupRemoved) XXX_Size() int {
	return xxx_messageInfo_AgentChangeEvent_InstanceGroupRemoved.Size(m)
}
func (m *AgentChangeEvent_InstanceGroupRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentChangeEvent_InstanceGroupRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_AgentChangeEvent_InstanceGroupRemoved proto.InternalMessageInfo

func (m *AgentChangeEvent_InstanceGroupRemoved) GetInstanceGroupId() string {
	if m != nil {
		return m.InstanceGroupId
	}
	return ""
}

// / Sent whenever 'AgentInstance' state changes, including initial (add)/final (terminate) updates.
type AgentChangeEvent_InstanceUpdate struct {
	Instance             *AgentInstance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AgentChangeEvent_InstanceUpdate) Reset()         { *m = AgentChangeEvent_InstanceUpdate{} }
func (m *AgentChangeEvent_InstanceUpdate) String() string { return proto.CompactTextString(m) }
func (*AgentChangeEvent_InstanceUpdate) ProtoMessage()    {}
func (*AgentChangeEvent_InstanceUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{5, 2}
}
func (m *AgentChangeEvent_InstanceUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentChangeEvent_InstanceUpdate.Unmarshal(m, b)
}
func (m *AgentChangeEvent_InstanceUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentChangeEvent_InstanceUpdate.Marshal(b, m, deterministic)
}
func (dst *AgentChangeEvent_InstanceUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentChangeEvent_InstanceUpdate.Merge(dst, src)
}
func (m *AgentChangeEvent_InstanceUpdate) XXX_Size() int {
	return xxx_messageInfo_AgentChangeEvent_InstanceUpdate.Size(m)
}
func (m *AgentChangeEvent_InstanceUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentChangeEvent_InstanceUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_AgentChangeEvent_InstanceUpdate proto.InternalMessageInfo

func (m *AgentChangeEvent_InstanceUpdate) GetInstance() *AgentInstance {
	if m != nil {
		return m.Instance
	}
	return nil
}

// / Sent whenever 'AgentInstance' is removed.
type AgentChangeEvent_InstanceRemoved struct {
	InstanceId           string   `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentChangeEvent_InstanceRemoved) Reset()         { *m = AgentChangeEvent_InstanceRemoved{} }
func (m *AgentChangeEvent_InstanceRemoved) String() string { return proto.CompactTextString(m) }
func (*AgentChangeEvent_InstanceRemoved) ProtoMessage()    {}
func (*AgentChangeEvent_InstanceRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{5, 3}
}
func (m *AgentChangeEvent_InstanceRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentChangeEvent_InstanceRemoved.Unmarshal(m, b)
}
func (m *AgentChangeEvent_InstanceRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentChangeEvent_InstanceRemoved.Marshal(b, m, deterministic)
}
func (dst *AgentChangeEvent_InstanceRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentChangeEvent_InstanceRemoved.Merge(dst, src)
}
func (m *AgentChangeEvent_InstanceRemoved) XXX_Size() int {
	return xxx_messageInfo_AgentChangeEvent_InstanceRemoved.Size(m)
}
func (m *AgentChangeEvent_InstanceRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentChangeEvent_InstanceRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_AgentChangeEvent_InstanceRemoved proto.InternalMessageInfo

func (m *AgentChangeEvent_InstanceRemoved) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

// / A marker notification, indicating that all known agent state was streamed to the client.
type AgentChangeEvent_SnapshotEnd struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentChangeEvent_SnapshotEnd) Reset()         { *m = AgentChangeEvent_SnapshotEnd{} }
func (m *AgentChangeEvent_SnapshotEnd) String() string { return proto.CompactTextString(m) }
func (*AgentChangeEvent_SnapshotEnd) ProtoMessage()    {}
func (*AgentChangeEvent_SnapshotEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{5, 4}
}
func (m *AgentChangeEvent_SnapshotEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentChangeEvent_SnapshotEnd.Unmarshal(m, b)
}
func (m *AgentChangeEvent_SnapshotEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentChangeEvent_SnapshotEnd.Marshal(b, m, deterministic)
}
func (dst *AgentChangeEvent_SnapshotEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentChangeEvent_SnapshotEnd.Merge(dst, src)
}
func (m *AgentChangeEvent_SnapshotEnd) XXX_Size() int {
	return xxx_messageInfo_AgentChangeEvent_SnapshotEnd.Size(m)
}
func (m *AgentChangeEvent_SnapshotEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentChangeEvent_SnapshotEnd.DiscardUnknown(m)
}

var xxx_messageInfo_AgentChangeEvent_SnapshotEnd proto.InternalMessageInfo

type AgentQuery struct {
	// / (Required) Requested page number/size.
	Page *Page `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// / (Optional) Collection of fields and their values for filtering.
	// Available query criteria:
	// instanceIds - list of agent instance ids
	// instanceGroupIds - list of server group ids
	// deploymentState - agent deployment state
	// overrideState - override state of an agent
	// healthState - current agent health state
	FilteringCriteria map[string]string `protobuf:"bytes,2,rep,name=filteringCriteria,proto3" json:"filteringCriteria,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// / (Optional) If set, only field values explicitly given in this parameter will be returned
	// This does not include certain attributes like 'id', 'instanceGroupId' which are always returned.
	// If nested field value is provided, only the explicitly listed nested fields will be returned.
	Fields               []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentQuery) Reset()         { *m = AgentQuery{} }
func (m *AgentQuery) String() string { return proto.CompactTextString(m) }
func (*AgentQuery) ProtoMessage()    {}
func (*AgentQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{6}
}
func (m *AgentQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentQuery.Unmarshal(m, b)
}
func (m *AgentQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentQuery.Marshal(b, m, deterministic)
}
func (dst *AgentQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentQuery.Merge(dst, src)
}
func (m *AgentQuery) XXX_Size() int {
	return xxx_messageInfo_AgentQuery.Size(m)
}
func (m *AgentQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentQuery.DiscardUnknown(m)
}

var xxx_messageInfo_AgentQuery proto.InternalMessageInfo

func (m *AgentQuery) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *AgentQuery) GetFilteringCriteria() map[string]string {
	if m != nil {
		return m.FilteringCriteria
	}
	return nil
}

func (m *AgentQuery) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Id struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{7}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (dst *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(dst, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AgentInstanceGroups struct {
	AgentInstanceGroups  []*AgentInstanceGroup `protobuf:"bytes,1,rep,name=agentInstanceGroups,proto3" json:"agentInstanceGroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AgentInstanceGroups) Reset()         { *m = AgentInstanceGroups{} }
func (m *AgentInstanceGroups) String() string { return proto.CompactTextString(m) }
func (*AgentInstanceGroups) ProtoMessage()    {}
func (*AgentInstanceGroups) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{8}
}
func (m *AgentInstanceGroups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInstanceGroups.Unmarshal(m, b)
}
func (m *AgentInstanceGroups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInstanceGroups.Marshal(b, m, deterministic)
}
func (dst *AgentInstanceGroups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInstanceGroups.Merge(dst, src)
}
func (m *AgentInstanceGroups) XXX_Size() int {
	return xxx_messageInfo_AgentInstanceGroups.Size(m)
}
func (m *AgentInstanceGroups) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInstanceGroups.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInstanceGroups proto.InternalMessageInfo

func (m *AgentInstanceGroups) GetAgentInstanceGroups() []*AgentInstanceGroup {
	if m != nil {
		return m.AgentInstanceGroups
	}
	return nil
}

type AgentInstances struct {
	AgentInstances       []*AgentInstance `protobuf:"bytes,1,rep,name=agentInstances,proto3" json:"agentInstances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AgentInstances) Reset()         { *m = AgentInstances{} }
func (m *AgentInstances) String() string { return proto.CompactTextString(m) }
func (*AgentInstances) ProtoMessage()    {}
func (*AgentInstances) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{9}
}
func (m *AgentInstances) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInstances.Unmarshal(m, b)
}
func (m *AgentInstances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInstances.Marshal(b, m, deterministic)
}
func (dst *AgentInstances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInstances.Merge(dst, src)
}
func (m *AgentInstances) XXX_Size() int {
	return xxx_messageInfo_AgentInstances.Size(m)
}
func (m *AgentInstances) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInstances.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInstances proto.InternalMessageInfo

func (m *AgentInstances) GetAgentInstances() []*AgentInstance {
	if m != nil {
		return m.AgentInstances
	}
	return nil
}

type TierUpdate struct {
	InstanceGroupId      string   `protobuf:"bytes,1,opt,name=instanceGroupId,proto3" json:"instanceGroupId,omitempty"`
	Tier                 Tier     `protobuf:"varint,2,opt,name=tier,proto3,enum=com.netflix.titus.Tier" json:"tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TierUpdate) Reset()         { *m = TierUpdate{} }
func (m *TierUpdate) String() string { return proto.CompactTextString(m) }
func (*TierUpdate) ProtoMessage()    {}
func (*TierUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{10}
}
func (m *TierUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TierUpdate.Unmarshal(m, b)
}
func (m *TierUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TierUpdate.Marshal(b, m, deterministic)
}
func (dst *TierUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TierUpdate.Merge(dst, src)
}
func (m *TierUpdate) XXX_Size() int {
	return xxx_messageInfo_TierUpdate.Size(m)
}
func (m *TierUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TierUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TierUpdate proto.InternalMessageInfo

func (m *TierUpdate) GetInstanceGroupId() string {
	if m != nil {
		return m.InstanceGroupId
	}
	return ""
}

func (m *TierUpdate) GetTier() Tier {
	if m != nil {
		return m.Tier
	}
	return Tier_Flex
}

type InstanceGroupLifecycleStateUpdate struct {
	InstanceGroupId      string                      `protobuf:"bytes,1,opt,name=instanceGroupId,proto3" json:"instanceGroupId,omitempty"`
	LifecycleState       InstanceGroupLifecycleState `protobuf:"varint,2,opt,name=lifecycleState,proto3,enum=com.netflix.titus.InstanceGroupLifecycleState" json:"lifecycleState,omitempty"`
	Detail               string                      `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *InstanceGroupLifecycleStateUpdate) Reset()         { *m = InstanceGroupLifecycleStateUpdate{} }
func (m *InstanceGroupLifecycleStateUpdate) String() string { return proto.CompactTextString(m) }
func (*InstanceGroupLifecycleStateUpdate) ProtoMessage()    {}
func (*InstanceGroupLifecycleStateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{11}
}
func (m *InstanceGroupLifecycleStateUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGroupLifecycleStateUpdate.Unmarshal(m, b)
}
func (m *InstanceGroupLifecycleStateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGroupLifecycleStateUpdate.Marshal(b, m, deterministic)
}
func (dst *InstanceGroupLifecycleStateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGroupLifecycleStateUpdate.Merge(dst, src)
}
func (m *InstanceGroupLifecycleStateUpdate) XXX_Size() int {
	return xxx_messageInfo_InstanceGroupLifecycleStateUpdate.Size(m)
}
func (m *InstanceGroupLifecycleStateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGroupLifecycleStateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGroupLifecycleStateUpdate proto.InternalMessageInfo

func (m *InstanceGroupLifecycleStateUpdate) GetInstanceGroupId() string {
	if m != nil {
		return m.InstanceGroupId
	}
	return ""
}

func (m *InstanceGroupLifecycleStateUpdate) GetLifecycleState() InstanceGroupLifecycleState {
	if m != nil {
		return m.LifecycleState
	}
	return InstanceGroupLifecycleState_Inactive
}

func (m *InstanceGroupLifecycleStateUpdate) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type InstanceGroupAttributesUpdate struct {
	InstanceGroupId      string            `protobuf:"bytes,1,opt,name=instanceGroupId,proto3" json:"instanceGroupId,omitempty"`
	Attributes           map[string]string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InstanceGroupAttributesUpdate) Reset()         { *m = InstanceGroupAttributesUpdate{} }
func (m *InstanceGroupAttributesUpdate) String() string { return proto.CompactTextString(m) }
func (*InstanceGroupAttributesUpdate) ProtoMessage()    {}
func (*InstanceGroupAttributesUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{12}
}
func (m *InstanceGroupAttributesUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGroupAttributesUpdate.Unmarshal(m, b)
}
func (m *InstanceGroupAttributesUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGroupAttributesUpdate.Marshal(b, m, deterministic)
}
func (dst *InstanceGroupAttributesUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGroupAttributesUpdate.Merge(dst, src)
}
func (m *InstanceGroupAttributesUpdate) XXX_Size() int {
	return xxx_messageInfo_InstanceGroupAttributesUpdate.Size(m)
}
func (m *InstanceGroupAttributesUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGroupAttributesUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGroupAttributesUpdate proto.InternalMessageInfo

func (m *InstanceGroupAttributesUpdate) GetInstanceGroupId() string {
	if m != nil {
		return m.InstanceGroupId
	}
	return ""
}

func (m *InstanceGroupAttributesUpdate) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type AgentInstanceAttributesUpdate struct {
	AgentInstanceId      string            `protobuf:"bytes,1,opt,name=agentInstanceId,proto3" json:"agentInstanceId,omitempty"`
	Attributes           map[string]string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AgentInstanceAttributesUpdate) Reset()         { *m = AgentInstanceAttributesUpdate{} }
func (m *AgentInstanceAttributesUpdate) String() string { return proto.CompactTextString(m) }
func (*AgentInstanceAttributesUpdate) ProtoMessage()    {}
func (*AgentInstanceAttributesUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_titus_agent_api_0ec414022e92c4d2, []int{13}
}
func (m *AgentInstanceAttributesUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInstanceAttributesUpdate.Unmarshal(m, b)
}
func (m *AgentInstanceAttributesUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInstanceAttributesUpdate.Marshal(b, m, deterministic)
}
func (dst *AgentInstanceAttributesUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInstanceAttributesUpdate.Merge(dst, src)
}
func (m *AgentInstanceAttributesUpdate) XXX_Size() int {
	return xxx_messageInfo_AgentInstanceAttributesUpdate.Size(m)
}
func (m *AgentInstanceAttributesUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInstanceAttributesUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInstanceAttributesUpdate proto.InternalMessageInfo

func (m *AgentInstanceAttributesUpdate) GetAgentInstanceId() string {
	if m != nil {
		return m.AgentInstanceId
	}
	return ""
}

func (m *AgentInstanceAttributesUpdate) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*InstanceLifecycleStatus)(nil), "com.netflix.titus.InstanceLifecycleStatus")
	proto.RegisterType((*HealthStatus)(nil), "com.netflix.titus.HealthStatus")
	proto.RegisterType((*InstanceGroupLifecycleStatus)(nil), "com.netflix.titus.InstanceGroupLifecycleStatus")
	proto.RegisterType((*AgentInstance)(nil), "com.netflix.titus.AgentInstance")
	proto.RegisterMapType((map[string]string)(nil), "com.netflix.titus.AgentInstance.AttributesEntry")
	proto.RegisterType((*AgentInstanceGroup)(nil), "com.netflix.titus.AgentInstanceGroup")
	proto.RegisterMapType((map[string]string)(nil), "com.netflix.titus.AgentInstanceGroup.AttributesEntry")
	proto.RegisterType((*AgentChangeEvent)(nil), "com.netflix.titus.AgentChangeEvent")
	proto.RegisterType((*AgentChangeEvent_InstanceGroupUpdate)(nil), "com.netflix.titus.AgentChangeEvent.InstanceGroupUpdate")
	proto.RegisterType((*AgentChangeEvent_InstanceGroupRemoved)(nil), "com.netflix.titus.AgentChangeEvent.InstanceGroupRemoved")
	proto.RegisterType((*AgentChangeEvent_InstanceUpdate)(nil), "com.netflix.titus.AgentChangeEvent.InstanceUpdate")
	proto.RegisterType((*AgentChangeEvent_InstanceRemoved)(nil), "com.netflix.titus.AgentChangeEvent.InstanceRemoved")
	proto.RegisterType((*AgentChangeEvent_SnapshotEnd)(nil), "com.netflix.titus.AgentChangeEvent.SnapshotEnd")
	proto.RegisterType((*AgentQuery)(nil), "com.netflix.titus.AgentQuery")
	proto.RegisterMapType((map[string]string)(nil), "com.netflix.titus.AgentQuery.FilteringCriteriaEntry")
	proto.RegisterType((*Id)(nil), "com.netflix.titus.Id")
	proto.RegisterType((*AgentInstanceGroups)(nil), "com.netflix.titus.AgentInstanceGroups")
	proto.RegisterType((*AgentInstances)(nil), "com.netflix.titus.AgentInstances")
	proto.RegisterType((*TierUpdate)(nil), "com.netflix.titus.TierUpdate")
	proto.RegisterType((*InstanceGroupLifecycleStateUpdate)(nil), "com.netflix.titus.InstanceGroupLifecycleStateUpdate")
	proto.RegisterType((*InstanceGroupAttributesUpdate)(nil), "com.netflix.titus.InstanceGroupAttributesUpdate")
	proto.RegisterMapType((map[string]string)(nil), "com.netflix.titus.InstanceGroupAttributesUpdate.AttributesEntry")
	proto.RegisterType((*AgentInstanceAttributesUpdate)(nil), "com.netflix.titus.AgentInstanceAttributesUpdate")
	proto.RegisterMapType((map[string]string)(nil), "com.netflix.titus.AgentInstanceAttributesUpdate.AttributesEntry")
	proto.RegisterEnum("com.netflix.titus.InstanceLifecycleState", InstanceLifecycleState_name, InstanceLifecycleState_value)
	proto.RegisterEnum("com.netflix.titus.HealthState", HealthState_name, HealthState_value)
	proto.RegisterEnum("com.netflix.titus.InstanceGroupLifecycleState", InstanceGroupLifecycleState_name, InstanceGroupLifecycleState_value)
}

func init() {
	proto.RegisterFile("netflix/titus/titus_agent_api.proto", fileDescriptor_titus_agent_api_0ec414022e92c4d2)
}

var fileDescriptor_titus_agent_api_0ec414022e92c4d2 = []byte{
	// 1395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcb, 0x72, 0xdb, 0x36,
	0x17, 0x16, 0x25, 0xcb, 0xb6, 0x8e, 0x2c, 0x59, 0x86, 0xfd, 0x3b, 0x1c, 0xe6, 0xe6, 0x30, 0x7f,
	0x3b, 0xae, 0x3b, 0x23, 0xbb, 0x4a, 0x9a, 0x66, 0x3a, 0xed, 0x24, 0x4e, 0xe2, 0xc4, 0x9e, 0x24,
	0x8d, 0x4b, 0xdb, 0xbd, 0x64, 0x93, 0x42, 0x22, 0x2c, 0x61, 0x4c, 0x81, 0x1c, 0x02, 0x54, 0xa3,
	0x7d, 0x9f, 0xa1, 0x8b, 0xbe, 0x44, 0x9f, 0xa0, 0xcf, 0xd1, 0x6e, 0xbb, 0xed, 0x2b, 0x74, 0xd3,
	0x21, 0x48, 0x4a, 0x22, 0x05, 0xdd, 0x16, 0xd9, 0x68, 0x04, 0xe0, 0x9c, 0xef, 0x3b, 0x37, 0x9c,
	0x03, 0xc2, 0x5d, 0x46, 0xc4, 0xa5, 0x43, 0xdf, 0xef, 0x0b, 0x2a, 0x02, 0x1e, 0xfd, 0xbe, 0xc3,
	0x6d, 0xc2, 0xc4, 0x3b, 0xec, 0xd1, 0xba, 0xe7, 0xbb, 0xc2, 0x45, 0x1b, 0x2d, 0xb7, 0x5b, 0x8f,
	0x05, 0xeb, 0x52, 0xc4, 0xb8, 0xde, 0x76, 0xdd, 0xb6, 0x43, 0xf6, 0xa5, 0x40, 0x33, 0xb8, 0xdc,
	0x27, 0x5d, 0x4f, 0xf4, 0x23, 0x79, 0xe3, 0x96, 0x0a, 0xb4, 0x89, 0x39, 0x89, 0xce, 0xcd, 0x5f,
	0x34, 0xb8, 0x76, 0xc2, 0xb8, 0xc0, 0xac, 0x45, 0x5e, 0xd1, 0x4b, 0xd2, 0xea, 0xb7, 0x1c, 0x72,
	0x26, 0xb0, 0x08, 0x38, 0x7a, 0x04, 0x45, 0x2e, 0xb0, 0x20, 0xba, 0xb6, 0xa3, 0xed, 0x56, 0x1b,
	0x9f, 0xd4, 0xc7, 0xb8, 0xeb, 0x4a, 0x55, 0x62, 0x45, 0x7a, 0x68, 0x17, 0xd6, 0x1d, 0x1c, 0xb0,
	0x56, 0xe7, 0x9c, 0x76, 0x09, 0x17, 0xb8, 0xeb, 0xe9, 0x85, 0x1d, 0x6d, 0x77, 0xc9, 0xca, 0x6e,
	0x9b, 0x7f, 0x6a, 0xb0, 0x76, 0x4c, 0xb0, 0x23, 0x3a, 0x31, 0xb7, 0x01, 0xab, 0xdc, 0x0d, 0xfc,
	0x16, 0x39, 0xb1, 0x25, 0x7d, 0xc9, 0x1a, 0xac, 0xd1, 0xfd, 0xc4, 0xae, 0xbc, 0xb4, 0xeb, 0x96,
	0xc2, 0xae, 0x21, 0xd6, 0xc0, 0x98, 0x6d, 0x58, 0xb6, 0x89, 0xc0, 0xd4, 0x91, 0x36, 0x94, 0xac,
	0x78, 0x85, 0x6e, 0x40, 0x49, 0x0c, 0xcc, 0x5b, 0x92, 0xe6, 0x0d, 0x37, 0xd0, 0x23, 0x80, 0x96,
	0xdb, 0xf5, 0x5c, 0x46, 0x98, 0xe0, 0x7a, 0x71, 0xa7, 0xb0, 0x5b, 0x6e, 0xdc, 0x9e, 0x4a, 0x18,
	0x70, 0x6b, 0x44, 0xc5, 0xfc, 0x4d, 0x83, 0x1b, 0x49, 0x94, 0x5e, 0xf8, 0x6e, 0xe0, 0x65, 0xa3,
	0xfc, 0x2c, 0x1d, 0xe5, 0xfa, 0x94, 0x28, 0x8f, 0xeb, 0x2b, 0xbc, 0xcb, 0x4f, 0xf6, 0xae, 0x90,
	0xf1, 0xce, 0xfc, 0xbd, 0x00, 0x95, 0xc3, 0xb0, 0xc2, 0x12, 0x06, 0x54, 0x85, 0x3c, 0x4d, 0x22,
	0x9e, 0xa7, 0x76, 0x98, 0x42, 0x3a, 0xca, 0x7e, 0x62, 0xc7, 0x04, 0xd9, 0xed, 0x90, 0x89, 0x7a,
	0x87, 0xb6, 0xed, 0x13, 0xce, 0xe3, 0x10, 0x0f, 0x37, 0xc2, 0x7c, 0x76, 0x5c, 0x2e, 0x18, 0xee,
	0x12, 0x19, 0xe4, 0x92, 0x35, 0x58, 0xa3, 0x73, 0x58, 0x77, 0xd2, 0x41, 0xd1, 0x8b, 0x3b, 0xda,
	0x6e, 0xb9, 0xb1, 0x37, 0x6f, 0xc5, 0x05, 0xdc, 0xca, 0x42, 0xa0, 0xa7, 0xb0, 0xd6, 0x19, 0x49,
	0x8a, 0xbe, 0x2c, 0x21, 0x67, 0xe6, 0x2e, 0xa5, 0x84, 0x4e, 0x01, 0xb0, 0x10, 0x3e, 0x6d, 0x06,
	0x82, 0x70, 0x7d, 0x45, 0xa6, 0xff, 0x40, 0x01, 0x91, 0x0a, 0x62, 0xfd, 0x70, 0xa0, 0x72, 0xc4,
	0x84, 0xdf, 0xb7, 0x46, 0x30, 0x8c, 0xaf, 0x61, 0x3d, 0x73, 0x8c, 0x6a, 0x50, 0xb8, 0x22, 0xfd,
	0x38, 0xe8, 0xe1, 0x5f, 0xb4, 0x05, 0xc5, 0x1e, 0x76, 0x02, 0x12, 0xc7, 0x3a, 0x5a, 0x7c, 0x99,
	0x7f, 0xa8, 0x99, 0xbf, 0x16, 0x01, 0xa5, 0xc8, 0x64, 0xf8, 0xc7, 0xd2, 0x66, 0xc2, 0x5a, 0x92,
	0x9f, 0xf3, 0xbe, 0x97, 0xe0, 0xa4, 0xf6, 0x90, 0x05, 0x1b, 0xc9, 0xda, 0x22, 0xd1, 0xe5, 0x8a,
	0x12, 0x57, 0x6e, 0xfc, 0x5f, 0xe1, 0x62, 0x22, 0xf3, 0x8c, 0x76, 0x09, 0xe3, 0xd4, 0x65, 0xd6,
	0xb8, 0x3a, 0xfa, 0x14, 0x96, 0x04, 0x25, 0xbe, 0x4c, 0x71, 0xb5, 0x71, 0x4d, 0x01, 0x73, 0x4e,
	0x89, 0x6f, 0x49, 0xa1, 0xd0, 0xef, 0x2e, 0x65, 0x32, 0xd7, 0x15, 0x2b, 0xfc, 0x8b, 0x74, 0x58,
	0xb1, 0x09, 0xa7, 0x3e, 0xb1, 0x65, 0xba, 0x2a, 0x56, 0xb2, 0x0c, 0x4f, 0x5a, 0x81, 0xef, 0x13,
	0x26, 0xf4, 0x95, 0xe8, 0x24, 0x5e, 0x4a, 0x14, 0xfc, 0x5e, 0x5f, 0x8d, 0x51, 0xf0, 0x7b, 0x59,
	0xb3, 0xfc, 0x95, 0xec, 0x30, 0x47, 0x0c, 0x37, 0x1d, 0x62, 0xeb, 0xa5, 0x1d, 0x6d, 0x77, 0xd5,
	0xca, 0x6e, 0xa3, 0x3a, 0x20, 0xca, 0xcf, 0x89, 0xdf, 0xa5, 0x0c, 0x0b, 0x92, 0x08, 0x83, 0x14,
	0x56, 0x9c, 0xa0, 0x1f, 0xc7, 0x2b, 0xb5, 0x2c, 0x03, 0xb6, 0xbf, 0xd0, 0xad, 0x55, 0x95, 0xab,
	0xa2, 0x57, 0xae, 0x29, 0x7b, 0x25, 0xba, 0x48, 0xd5, 0x64, 0x45, 0xd6, 0xe4, 0xe7, 0xb3, 0x6a,
	0x52, 0x1a, 0xf1, 0x21, 0x0b, 0xf3, 0xaf, 0x65, 0xa8, 0x49, 0xc6, 0xa7, 0x1d, 0xcc, 0xda, 0xe4,
	0xa8, 0x17, 0xe6, 0xe6, 0x0a, 0x36, 0x53, 0x6d, 0xe2, 0xc2, 0xb3, 0x93, 0x4e, 0x57, 0x6e, 0x7c,
	0x31, 0xc9, 0xe6, 0x11, 0x84, 0x74, 0x10, 0x23, 0xf5, 0xe3, 0x9c, 0xa5, 0x42, 0x45, 0x0c, 0xb6,
	0x52, 0xdb, 0x16, 0xe9, 0xba, 0x3d, 0x12, 0xf5, 0xab, 0x72, 0xe3, 0xe1, 0xc2, 0x6c, 0xb1, 0xfe,
	0x71, 0xce, 0x52, 0xe2, 0xa2, 0x4b, 0xd8, 0xc4, 0xa3, 0x21, 0x8e, 0x9d, 0x8b, 0x6e, 0x50, 0x63,
	0x11, 0xba, 0xa1, 0x5f, 0x0a, 0x40, 0x44, 0x61, 0x2b, 0xb5, 0x9d, 0xf8, 0xb5, 0x24, 0x89, 0xee,
	0x2d, 0x42, 0x34, 0xe2, 0x92, 0x0a, 0x12, 0x9d, 0x41, 0x99, 0x33, 0xec, 0xf1, 0x8e, 0x2b, 0x8e,
	0x98, 0x1d, 0x77, 0xe1, 0xfd, 0x79, 0x18, 0xce, 0x86, 0x6a, 0xc7, 0x39, 0x6b, 0x14, 0xc5, 0x68,
	0xc2, 0xa6, 0x22, 0x8b, 0xe8, 0x25, 0x54, 0x52, 0x61, 0x8d, 0xab, 0xe2, 0xa3, 0xb9, 0x2a, 0xd9,
	0x4a, 0xeb, 0x1a, 0x8f, 0x61, 0x4b, 0x95, 0x3b, 0xd5, 0xf8, 0xd2, 0x94, 0xe3, 0xcb, 0xf8, 0x06,
	0xaa, 0x99, 0xb8, 0x7f, 0x05, 0xab, 0x89, 0x50, 0x6c, 0xdb, 0xce, 0x2c, 0xdb, 0xac, 0x81, 0x86,
	0xf1, 0x19, 0xac, 0x67, 0xa3, 0x7b, 0x0b, 0x20, 0x39, 0x1e, 0xd8, 0x31, 0xb2, 0x63, 0x54, 0xa0,
	0x3c, 0x12, 0xc6, 0x27, 0x2b, 0x50, 0x94, 0xb1, 0x35, 0xff, 0xd5, 0x00, 0x24, 0xcd, 0xb7, 0x01,
	0xf1, 0xfb, 0x61, 0x8f, 0xf5, 0x70, 0x3b, 0xb1, 0x49, 0xd5, 0x63, 0x4f, 0x71, 0x9b, 0x58, 0x52,
	0x08, 0x35, 0x61, 0xe3, 0x92, 0x3a, 0x82, 0xf8, 0x94, 0xb5, 0x9f, 0xfa, 0x34, 0xfc, 0x83, 0xf5,
	0xbc, 0xec, 0x19, 0xf7, 0x27, 0x79, 0x23, 0x69, 0xea, 0xcf, 0xb3, 0x6a, 0x51, 0xcb, 0x18, 0x87,
	0x0b, 0xdf, 0x1e, 0x97, 0x94, 0x38, 0x76, 0xf4, 0x3e, 0x2a, 0x59, 0xf1, 0xca, 0x78, 0x06, 0xdb,
	0x6a, 0x90, 0x85, 0x1a, 0xcb, 0x16, 0xe4, 0x4f, 0xec, 0xec, 0x80, 0x33, 0x19, 0x6c, 0x8e, 0x57,
	0x05, 0x47, 0xdf, 0x67, 0xee, 0x64, 0xb4, 0xad, 0x6b, 0xd2, 0xe1, 0x39, 0x4b, 0x4b, 0x85, 0x60,
	0xbe, 0x85, 0x6a, 0x4a, 0x94, 0xa3, 0x63, 0xa8, 0xa6, 0x04, 0x13, 0x96, 0xd9, 0x45, 0x92, 0xd1,
	0x33, 0x5b, 0x00, 0xe1, 0x54, 0x8c, 0xcb, 0x6e, 0xee, 0x92, 0x1d, 0x0c, 0xdb, 0xfc, 0x1c, 0xc3,
	0xd6, 0xfc, 0x43, 0x83, 0x3b, 0x53, 0xde, 0x91, 0x0b, 0x93, 0x7f, 0x07, 0xd5, 0xd4, 0x08, 0x4b,
	0x5e, 0xe3, 0x8b, 0xbe, 0x5f, 0x33, 0x28, 0x93, 0x9e, 0xe9, 0xe6, 0x3f, 0x1a, 0xdc, 0x4c, 0xe1,
	0x0c, 0x87, 0xd5, 0xc2, 0xb6, 0xff, 0x94, 0x9a, 0xa0, 0xd1, 0x6d, 0x78, 0x3c, 0xcb, 0xee, 0x2c,
	0xdf, 0x87, 0x1c, 0xa6, 0xa1, 0xb3, 0xa9, 0x9a, 0x51, 0x39, 0x9b, 0xaa, 0xa2, 0xa1, 0xb3, 0x99,
	0xed, 0xb9, 0x9d, 0x9d, 0xca, 0xf7, 0x01, 0x9d, 0xdd, 0xe3, 0xb0, 0xad, 0xfe, 0x8c, 0x44, 0x08,
	0xaa, 0x67, 0x02, 0xfb, 0xe2, 0x84, 0x51, 0x41, 0xb1, 0x20, 0x76, 0x2d, 0x87, 0xca, 0xb0, 0x22,
	0xf7, 0x88, 0x5d, 0xd3, 0xd0, 0x06, 0x54, 0x5e, 0x52, 0xc7, 0x19, 0x9e, 0xe7, 0xa3, 0x73, 0xd7,
	0xf3, 0x88, 0x5d, 0x2b, 0x20, 0x7d, 0x38, 0x16, 0xa2, 0x2a, 0x67, 0x57, 0xcc, 0xfd, 0x99, 0xd5,
	0x96, 0xf6, 0x1e, 0x40, 0x79, 0xe4, 0x1b, 0x31, 0xd4, 0x4a, 0xce, 0x24, 0x45, 0x74, 0xd6, 0xaf,
	0x69, 0xa8, 0x02, 0xa5, 0x0b, 0xd6, 0x89, 0x97, 0xf9, 0xbd, 0x0b, 0xb8, 0x3e, 0xa5, 0x9a, 0xd1,
	0x1a, 0xac, 0x9e, 0x30, 0xdc, 0x12, 0xb4, 0x47, 0x6a, 0x39, 0x04, 0xb0, 0x7c, 0x18, 0xfd, 0x97,
	0x38, 0xa7, 0x1d, 0xcc, 0x89, 0xfd, 0x26, 0x10, 0xb5, 0x7c, 0xb8, 0x94, 0x63, 0x21, 0x7c, 0x57,
	0xd6, 0x0a, 0x8d, 0xbf, 0x97, 0x61, 0x5b, 0x26, 0xe0, 0x35, 0x66, 0xb8, 0x4d, 0xba, 0x84, 0x89,
	0x33, 0xe2, 0xf7, 0x68, 0x8b, 0xa0, 0x0b, 0xd8, 0x78, 0x41, 0xb2, 0x7d, 0x6e, 0xbb, 0x1e, 0x7d,
	0xf4, 0xd7, 0x93, 0x8f, 0xfe, 0xfa, 0x51, 0xf8, 0xd1, 0x6f, 0x7c, 0x3c, 0x57, 0x8b, 0xe3, 0x66,
	0x0e, 0x59, 0x50, 0xcb, 0xc2, 0xa2, 0xff, 0xa9, 0xee, 0x80, 0x6d, 0xcc, 0xd7, 0x37, 0xcd, 0x1c,
	0x7a, 0x2d, 0x31, 0xd3, 0x1f, 0x94, 0x13, 0x30, 0x67, 0x76, 0x49, 0x33, 0x87, 0x7e, 0x00, 0xf4,
	0x9c, 0x32, 0x3b, 0xd3, 0x77, 0x6f, 0x4e, 0x1d, 0x5b, 0xc6, 0x9d, 0x59, 0xc0, 0x91, 0xf3, 0xd7,
	0xa2, 0xba, 0x4e, 0x79, 0x10, 0x76, 0x4b, 0x25, 0xfc, 0xb0, 0x3b, 0x1b, 0x13, 0x02, 0x6f, 0xe6,
	0x10, 0x87, 0x3b, 0x0a, 0xcc, 0x4c, 0x7d, 0xdc, 0x5f, 0xac, 0x3b, 0xce, 0x24, 0xbd, 0x82, 0x9b,
	0x0a, 0xd2, 0xe1, 0x6d, 0x44, 0x07, 0x8b, 0xb6, 0xb5, 0x79, 0xc8, 0x26, 0xb4, 0x0a, 0x74, 0xb0,
	0x68, 0x5b, 0x99, 0x42, 0x76, 0x0a, 0x95, 0x37, 0x4d, 0x4e, 0xfc, 0x5e, 0xc4, 0x36, 0xb9, 0xe4,
	0xef, 0xce, 0xf1, 0x3c, 0x35, 0x73, 0x07, 0xda, 0x93, 0x07, 0x70, 0x7b, 0x5c, 0xb2, 0xed, 0x7b,
	0xad, 0x08, 0xb1, 0x4d, 0xd8, 0x93, 0xe8, 0x99, 0x75, 0x1a, 0x2e, 0x4f, 0xb5, 0xb7, 0x45, 0x29,
	0xd2, 0x5c, 0x96, 0xc7, 0xf7, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x00, 0xb6, 0x6c, 0x6f, 0xa0,
	0x13, 0x00, 0x00,
}
